blank_issues_enabled: true
contact_links:
  - name: 💬 Discord PersonaDLE
    url: https://discord.gg/wpMdGGDp3y
    about: Pour discuter, poser une question ou signaler vite fait sans ouvrir d'issue.
