  /**
   * A list of character names used for silhouette mode autocompletion.
   */
  export const personas = [
    "Tohru Adachi",
    "Ai Ebihara",
    "Aigis",
    "Akihiko Sanada",
    "Ann Takamaki",
    "Ayane Matsunaga",
    "Bebe",
    "Bunkichi",
    "Caroline & Justine",
    "Chidori Yoshino",
    "Chie Satonaka",
    "Chihaya Mifune",
    "Chihiro Fushimi",
    "Daisuke Nagase",
    "Ryotaro Dojima",
    "Mr. Edogawa",
    "Elizabeth",
    "Eri Minami",
    "Fox",
    "Futaba Sakura",
    "Fuuka Yamagishi",
    "Goro Akechi",
    "Haru Okumura",
    "Mamoru Hayase",
    "Hidetoshi Odagiri",
    "Hifumi Togo",
    "Hisano Kuroda",
    "Ichiko Ohya",
    "Igor",
    "Shuji Ikutsuki",
    "Munehisa Iwai",
    "Jin Shirato",
    "Jose",
    "Junpei Iori",
    "Kanji Tatsumi",
    "Kazushi Miyamoto",
    "Keisuke Hiraga",
    "Ken Amada",
    "Kenji Tomochika",
    "Koromaru",
    "Kotone Shiomi",
    "Kou Ichijo",
    "Labrys",
    "Lavenza",
    "Maiko Oohashi",
    "Makoto Niijima",
    "Margaret",
    "Marie",
    "Maya",
    "Metis",
    "Yuuki Mishima",
    "Mitsuko",
    "Mitsuru Kirijo",
    "Morgana",
    "Mutatsu",
    "Nanako Dojima",
    "Naoki Konishi",
    "Naoto Shirogane",
    "Nozomi Suemitsu",
    "Pharos",
    "Ren Amamiya",
    "Rio Iwasaki",
    "Rise Kujikawa",
    "Ryoji Mochizuki",
    "Ryuji Sakamoto",
    "Sadayo Kawakami",
    "Sae Niijima",
    "Saori Hasegawa",
    "Sayako Uehara",
    "Shinjiro Aragaki",
    "Shinya Oda",
    "Sho Minazuki",
    "Shu Nakajima",
    "Sojiro Sakura",
    "Sumire Yoshizawa",
    "Tae Takemi",
    "Takaya Sakaki",
    "Takuto Maruki",
    "Teddie",
    "Theodore",
    "Toranosuke Yoshida",
    "Yosuke Hanamura",
    "Yu Narukami",
    "Yukari Takeba",
    "Makoto Yuki",
    "Yukiko Amagi",
    "Yumi Ozawa",
    "Yusuke Kitagawa",
    "Sophia",
    "Zenkichi Hasegawa",
    "Nagisa Kamishiro",
    "Lufel",
    "Motoha Arai",
    "Shun Kano",
    "Riko Tanemura",
    "Shoki Ikenami",
    "Seiji Shiratori",
    "Kotone Montagne",
    "Yukimi Fujikawa",
    "Tomoko Noge",
    "Leo Kamiyama",
    "Yaoling Li",
    "Kiyoshi Kurotani",
    "Kayo Tomiyama",
    "Miyu Sahara",
    "Toshiya Sumi",
    "Haruna Nishimori",
    "YUI",
    "Minami Miyashita",
    "Chizuko Nagao",
    "Yumi Shiina",
    "Ayaka Sakai",
    "Kira Kitazato",
    "Masaki Ashiya",
    "Runa Dogenzaka",
    "Mio Natsukawa",
    "Mayumi Hashimoto",
    "Manaka Nagao",
    "Ichigo Shikano",
    "Merope",

  // === Persona 1 & 2 ===

  "Naoya Todou",
  "Maki Sonomura",
  "Masao Inaba",
  "Kei Nanjo",
  "Yukino Mayuzumi",
  "Hidehiko Uesugi",
  "Eriko Kirishima",
  "Yuka Ayase",
  "Reiji Kido",
  "Tatsuya Suou",
  "Maya Amano",
  "Lisa Silverman",
  "Jun Kurosu",
  "Eikichi Mishina",
  "Baofu",
  "Joker",
  "Izanami",

  ];
