export const portraitsMapSilhouette = {
  "Ai Ebihara": "Ai",
  "Ann Takamaki": "Ann",
  "Ayane Matsunaga": "Ayane",
  "Bebe": "Bebe",
  "Bunkichi": "Bunkichi",
  "Caroline & Justine": "Caroline_and_Justine",
  "Chidori Yoshino": "Chidori",
  "Chie Satonaka": "Chie",
  "Chihaya Mifune": "Chihaya",
  "Chihiro Fushimi": "Chihiro",
  "Daisuke Nagase": "Daisuke",
  "Elizabeth": "Elizabeth",
  "Eri Minami": "Eri",
  "Fox": "Fox",
  "Futaba Sakura": "Futaba",
  "Fuuka Yamagishi": "Fuuka",
  "Goro Akechi": "Goro",
  "Haru Okumura": "Haru",
  "Hatsune Miku": "Miku",
  "Hidetoshi Odagiri": "Hidetoshi",
  "Hifumi Togo": "Hifumi",
  "Hisano Kuroda": "Hisano",
  "Ichiko Ohya": "Ohya",
  "Igor": "Igor",
  "Munehisa Iwai": "Iwai",
  "Mamoru Hayase": "Hayase",
  "Jin Shirato": "Jin",
  "Jose": "Jose",
  "Junpei Iori": "Junpei",
  "Kanji Tatsumi": "Kanji",
  "Kazushi Miyamoto": "Kazushi",
  "Keisuke Hiraga": "Keisuke",
  "Ken Amada": "Ken",
  "Kenji Tomochika": "Kenji",
  "Koromaru": "Koromaru",
  "Kotone Shiomi": "Kotone",
  "Kou Ichijo": "Kou",
  "Labrys": "Labrys",
  "Lavenza": "Lavenza",
  "Maiko": "Maiko",
  "Makoto Niijima": "Makoto",
  "Margaret": "Margaret",
  "Marie": "Marie",
  "Metis": "Metis",
  "Yuuki Mishima": "Mishima",
  "Mitsuko": "Mitsuko",
  "Mitsuru Kirijo": "Mitsuru",
  "Morgana": "Morgana",
  "Mr. Edogawa": "Edgoawa",
  "Mutatsu": "Mutatsu",
  "Ryotaro Dojima": "Dojima",
  "Nanako Dojima": "Nanako",
  "Naoki Konishi": "Naoki",
  "Naoto Shirogane": "Naoto",
  "Naoya Todou": "Naoya",
  "Nozomi Suemitsu": "Nozomi",
  "Pharos": "Pharos",
  "President Tanaka": "Tanaka",
  "Ren Amamiya": "Ren",
  "Rise Kujikawa": "Rise",
  "Rio Iwasaki": "Rio",
  "Ryoji Mochizuki": "Ryoji",
  "Ryuji Sakamoto": "Ryuji",
  "Sadayo Kawakami": "Kawakami",
  "Sae Niijima": "Sae",
  "Saori Hasegawa": "Saori",
  "Sayako Uehara": "Sayako",
  "Shinjiro Aragaki": "Shinjiro",
  "Shinya Oda": "Oda",
  "Sho Minazuki": "Sho",
  "Shu Nakajima": "Shu",
  "Sojiro Sakura": "Sojiro",
  "Sumire Yoshizawa": "Sumire",
  "Tae Takemi": "Takemi",
  "Takaya Sakaki": "Takaya",
  "Takuto Maruki": "Maruki",
  "Teddie": "Teddie",
  "Theodore": "Theodore",
  "Tohru Adachi": "Adachi",
  "Toranosuke Yoshida": "Yoshida",
  "Yosuke Hanamura": "Yosuke",
  "Yu Narukami": "Yu",
  "Yukari Takeba": "Yukari",
  "Yukiko Amagi": "Yukiko",
  "Yumi Ozawa": "Yumi",
  "Yusuke Kitagawa": "Yusuke",
  "Makoto Yuki": "Yuki",
  "Shuji Ikutsuki": "Ikutsuki",
  "Ayaka Sakai": "Ayaka",
  "Chizuko Nagao": "Chizuko",
  "Ichigo Shikano": "Ichigo",
  "Kayo Tomiyama": "Kayo",
  "Kira Kitazato": "Kira",
  "Kiyoshi Kurotani": "Kiyoshi",
  "Kotone Montagne": "Montagne",
  "Leo Kamiyama": "Reo",
  "Lufel": "Lufel",
  "Manaka Nagao": "Manaka",
  "Masaki Ashiya": "Masaki",
  "Mayumi Hashimoto": "Mayumi",
  "Merope": "Merope",
  "Minami Miyashita": "Minami",
  "Mio Natsukawa": "Mio",
  "Miyu Sahara": "Miyu",
  "Nagisa Kamishiro": "Nagisa",
  "Riko Tanemura": "Riko",
  "Runa Dogenzaka": "Runa",
  "Seiji Shiratori": "Seiji",
  "Aran Hirano": "Aran",
  "Narumi Nashimoto": "Narumi",
  "Kumi Katayama": "Kumi_Katayama",
  "Shoki Ikenami": "Shoki",
  "Shun Kano": "Shun",
  "Tomoko Noge": "Tomoko",
  "Toshiya Sumi": "Toshiya",
  "Yaoling Li": "Yaoling",
  "YUI": "YUI",
  "Yukimi Fujikawa": "Yukimi",
  "Yumi Shiina": "Yumi_S",
  "Aigis": "Aigis",
  "Akihiko Sanada": "Akihiko",
  "Sophia": "Sophia",
  "Zenkichi Hasegawa": "Zenkichi",
  "Motoha Arai": "Arai", // déjà présent mais sous "Arai", à renommer si tu veux l'uniformiser
  "Haruna Nishimori": "Haruna",
  "Maiko Oohashi": "Maiko",
  "Maya": "Maya", // seulement si le fichier s'appelle Maya_silhouette.webp

  "Maya Amano": "Maya_A",
  "Joker": "JOKER",
  "Izanami": "Izanami",

  // Entités / Boss finaux
  "Nyx": "Nyx",
  "Yaldabaoth": "Yaldabaoth",

  "Erina": "Erina",
  "Toshiro Kasukabe": "Toshiro",

  "Saki Konishi": "Saki",
  "Mayumi Yamano": "Mayumi_Yamano",
  "Shin Kanzato": "Shin_Kanzato",
  "Jun Kanzato": "Jun_Kanzato",
  "Ryo Kanzato": "Ryo_Kanzato",

  // Variantes P4AU — portrait propre à Arena Ultimax, distinct du portrait P3.
  // Sans ces entrées le fallback `nom.split(" ")[0]` renverrait le portrait P3
  // (« Aigis »), rendant les deux versions indiscernables dans la liste.
  "Aigis (P4AU)": "Aigis_P4AU",
  "Akihiko Sanada (P4AU)": "Akihiko_P4AU",
  "Fuuka Yamagishi (P4AU)": "Fuuka_P4AU",
  "Junpei Iori (P4AU)": "Junpei_P4AU",
  "Ken Amada (P4AU)": "Ken_P4AU",
  "Koromaru (P4AU)": "Koromaru_P4AU",
  "Mitsuru Kirijo (P4AU)": "Mitsuru_P4AU",
  "Yukari Takeba (P4AU)": "Yukari_P4AU",
};
