export const silhouetteCharacters = [
  { nom: "Tohru Adachi", image: "Adachi_silhouette", opus: ["P4"] },
  { nom: "Ai Ebihara", image: "Ai_silhouette", opus: ["P4"] },
  { nom: "Aigis", image: "Aigis_silhouette", opus: ["P3"] },
  { nom: "Akihiko Sanada", image: "Akihiko_silhouette", opus: ["P3"] },
  { nom: "Ann Takamaki", image: "Ann_silhouette", opus: ["P5"] },
  { nom: "Ayane Matsunaga", image: "Ayane_silhouette", opus: ["P4"] },
  { nom: "Bebe", image: "Bebe_silhouette", opus: ["P3"] },
  { nom: "Bunkichi", image: "Bunkichi_silhouette", opus: ["P3"] },
  { nom: "Caroline & Justine", image: "Caroline_and_Justine_silhouette", opus: ["P5"] }
, { nom: "Chidori Yoshino", image: "Chidori_silhouette", opus: ["P3"] },
  { nom: "Chie Satonaka", image: "Chie_silhouette", opus: ["P4"] },
  { nom: "Chihaya Mifune", image: "Chihaya_silhouette", opus: ["P5"] },
  { nom: "Chihiro Fushimi", image: "Chihiro_silhouette", opus: ["P3"] },
  { nom: "Daisuke Nagase", image: "Daisuke_silhouette", opus: ["P4"] },
  { nom: "Ryotaro Dojima", image: "Dojima_silhouette", opus: ["P4"] },
  { nom: "Mr. Edogawa", image: "Edgoawa_silhouette", opus: ["P3"] },
  { nom: "Elizabeth", image: "Elizabeth_silhouette", opus: ["P3"] },
  { nom: "Eri Minami", image: "Eri_silhouette", opus: ["P4"] },
  { nom: "Fox", image: "Fox_silhouette", opus: ["P4"] },
  { nom: "Futaba Sakura", image: "Futaba_silhouette", opus: ["P5"] },
  { nom: "Fuuka Yamagishi", image: "Fuuka_silhouette", opus: ["P3"] },
  { nom: "Goro Akechi", image: "Goro_silhouette", opus: ["P5"] },
  { nom: "Haru Okumura", image: "Haru_silhouette", opus: ["P5"] },
  { nom: "Mamoru Hayase", image: "Hayase_silhouette", opus: ["P3"] },
  { nom: "Hidetoshi Odagiri", image: "Hidetoshi_silhouette", opus: ["P3"] },
  { nom: "Hifumi Togo", image: "Hifumi_silhouette", opus: ["P5"] },
  { nom: "Hisano Kuroda", image: "Hisano_silhouette", opus: ["P4"] },
  { nom: "Ichiko Ohya", image: "Ohya_silhouette", opus: ["P5"] },
  { nom: "Igor", image: "Igor_silhouette", opus: ["P3", "P4", "P5"] },
  { nom: "Shuji Ikutsuki", image: "Ikutsuki_silhouette", opus: ["P3"] },
  { nom: "Munehisa Iwai", image: "Iwai_silhouette", opus: ["P5"] },
  { nom: "Jin Shirato", image: "Jin_silhouette", opus: ["P3"] },
  { nom: "Jose", image: "Jose_silhouette", opus: ["P5"] },
  { nom: "Junpei Iori", image: "Junpei_silhouette", opus: ["P3"] },
  { nom: "Kanji Tatsumi", image: "Kanji_silhouette", opus: ["P4"] },
  { nom: "Kazushi Miyamoto", image: "Kazushi_silhouette", opus: ["P3"] },
  { nom: "Keisuke Hiraga", image: "Keisuke_silhouette", opus: ["P3"] },
  { nom: "Ken Amada", image: "Ken_silhouette", opus: ["P3"] },
  { nom: "Kenji Tomochika", image: "Kenji_silhouette", opus: ["P3"] },
  { nom: "Koromaru", image: "Koromaru_silhouette", opus: ["P3"] },
  { nom: "Kotone Shiomi", image: "Kotone_silhouette", opus: ["P3"] },
  { nom: "Kou Ichijo", image: "Kou_silhouette", opus: ["P4"] },
  { nom: "Labrys", image: "Labrys_silhouette", opus: ["P4AU"] },
  { nom: "Lavenza", image: "Lavenza_silhouette", opus: ["P5"] },
  { nom: "Maiko Oohashi", image: "Maiko_silhouette", opus: ["P3"] },
  { nom: "Makoto Niijima", image: "Makoto_silhouette", opus: ["P5"] },
  { nom: "Margaret", image: "Margaret_silhouette", opus: ["P4"] },
  { nom: "Marie", image: "Marie_silhouette", opus: ["P4G"] },
  { nom: "Maya", image: "Maya_silhouette", opus: ["P3"] },
  { nom: "Metis", image: "Metis_silhouette", opus: ["P3FES"] },
  { nom: "Yuuki Mishima", image: "Mishima_silhouette", opus: ["P5"] },
  { nom: "Mitsuko", image: "Mitsuko_silhouette", opus: ["P3"] },
  { nom: "Mitsuru Kirijo", image: "Mitsuru_silhouette", opus: ["P3"] },
  { nom: "Morgana", image: "Morgana_silhouette", opus: ["P5"] },
  { nom: "Mutatsu", image: "Mutatsu_silhouette", opus: ["P3"] },
  { nom: "Nanako Dojima", image: "Nanako_silhouette", opus: ["P4"] },
  { nom: "Naoki Konishi", image: "Naoki_silhouette", opus: ["P4"] },
  { nom: "Naoto Shirogane", image: "Naoto_silhouette", opus: ["P4"] },
  { nom: "Nozomi Suemitsu", image: "Nozomi_silhouette", opus: ["P3"] },
  { nom: "Pharos", image: "Pharos_silhouette", opus: ["P3"] },
  { nom: "Ren Amamiya", image: "Ren_silhouette", opus: ["P5"] },
  { nom: "Rio Iwasaki", image: "Rio_silhouette", opus: ["P3P"] },
  { nom: "Rise Kujikawa", image: "Rise_silhouette", opus: ["P4"] },
  { nom: "Ryoji Mochizuki", image: "Ryoji_silhouette", opus: ["P3"] },
  { nom: "Ryuji Sakamoto", image: "Ryuji_silhouette", opus: ["P5"] },
  { nom: "Sadayo Kawakami", image: "Kawakami_silhouette", opus: ["P5"] },
  { nom: "Sae Niijima", image: "Sae_silhouette", opus: ["P5"] },
  { nom: "Saori Hasegawa", image: "Saori_silhouette", opus: ["P3P"] },
  { nom: "Sayako Uehara", image: "Sayako_silhouette", opus: ["P4"] },
  { nom: "Shinjiro Aragaki", image: "Shinjiro_silhouette", opus: ["P3"] },
  { nom: "Shinya Oda", image: "Oda_silhouette", opus: ["P5"] },
  { nom: "Sho Minazuki", image: "Sho_silhouette", opus: ["P4AU"] },
  { nom: "Shu Nakajima", image: "Shu_silhouette", opus: ["P4"] },
  { nom: "Sojiro Sakura", image: "Sojiro_silhouette", opus: ["P5"] },
  { nom: "Sumire Yoshizawa", image: "Sumire_silhouette", opus: ["P5R"] },
  { nom: "Tae Takemi", image: "Takemi_silhouette", opus: ["P5"] },
  { nom: "Takaya Sakaki", image: "Takaya_silhouette", opus: ["P3"] },
  { nom: "Takuto Maruki", image: "Maruki_silhouette", opus: ["P5R"] },
  { nom: "Teddie", image: "Teddie_silhouette", opus: ["P4"] },
  { nom: "Theodore", image: "Theodore_silhouette", opus: ["P3P"] },
  { nom: "Toranosuke Yoshida", image: "Yoshida_silhouette", opus: ["P5"] },
  { nom: "Yosuke Hanamura", image: "Yosuke_silhouette", opus: ["P4"] },
  { nom: "Yu Narukami", image: "Yu_silhouette", opus: ["P4"] },
  { nom: "Yukari Takeba", image: "Yukari_silhouette", opus: ["P3"] },
  { nom: "Makoto Yuki", image: "Yuki_silhouette", opus: ["P3"] },
  { nom: "Yukiko Amagi", image: "Yukiko_silhouette", opus: ["P4"] },
  { nom: "Yumi Ozawa", image: "Yumi_silhouette", opus: ["P4"] },
  { nom: "Yusuke Kitagawa", image: "Yusuke_silhouette", opus: ["P5"] },
  { nom: "Sophia", image: "Sophia_silhouette", opus: ["P5S"] },
  { nom: "Zenkichi Hasegawa", image: "Zenkichi_silhouette", opus: ["P5S"] },
  { nom: "Shuji Ikutsuki", image: "Ikutsuki_silhouette", opus: ["P3"] },
  { nom: "Motoha Arai", image: "Arai_silhouette", opus: ["P5X"] },
{ nom: "Ayaka Sakai", image: "Ayaka_silhouette", opus: ["P5X"] },
{ nom: "Haruna Nishimori", image: "Haruna_silhouette", opus: ["P5X"] },
{ nom: "Ichigo Shikano", image: "Ichigo_silhouette", opus: ["P5X"] },
{ nom: "Kayo Tomiyama", image: "Kayo_silhouette", opus: ["P5X"] },
{ nom: "Kira Kitazato", image: "Kira_silhouette", opus: ["P5X"] },
{ nom: "Kiyoshi Kurotani", image: "Kiyoshi_silhouette", opus: ["P5X"] },
{ nom: "Leo Kamiyama", image: "Leo_silhouette", opus: ["P5X"] },
{ nom: "Lufel", image: "Lufel_silhouette", opus: ["P5X"] },
{ nom: "Manaka Nagao", image: "Manaka_silhouette", opus: ["P5X"] },
{ nom: "Masaki Ashiya", image: "Masaki_silhouette", opus: ["P5X"] },
{ nom: "Mayumi Hashimoto", image: "Mayumi_silhouette", opus: ["P5X"] },
{ nom: "Merope", image: "Merope_silhouette", opus: ["P5X"] },
{ nom: "Minami Miyashita", image: "Minami_silhouette", opus: ["P5X"] },
{ nom: "Mio Natsukawa", image: "Mio_silhouette", opus: ["P5X"] },
{ nom: "Miyu Sahara", image: "Miyu_silhouette", opus: ["P5X"] },
{ nom: "Kotone Montagne", image: "Montagne_silhouette", opus: ["P5X"] },
{ nom: "Nagisa Kamishiro", image: "Nagisa_silhouette", opus: ["P5X"] },
{ nom: "Riko Tanemura", image: "Riko_silhouette", opus: ["P5X"] },
{ nom: "Runa Dogenzaka", image: "Runa_silhouette", opus: ["P5X"] },
{ nom: "Seiji Shiratori", image: "Seiji_silhouette", opus: ["P5X"] },
{ nom: "Shoki Ikenami", image: "Shoki_silhouette", opus: ["P5X"] },
{ nom: "Shun Kano", image: "Shun_silhouette", opus: ["P5X"] },
{ nom: "Tomoko Noge", image: "Tomoko_silhouette", opus: ["P5X"] },
{ nom: "Toshiya Sumi", image: "Toshiya_silhouette", opus: ["P5X"] },
{ nom: "Yaoling Li", image: "Yaoling_silhouette", opus: ["P5X"] },
{ nom: "YUI", image: "YUI_silhouette", opus: ["P5X"] },
{ nom: "Yukimi Fujikawa", image: "Yukimi_silhouette", opus: ["P5X"] },
{ nom: "Yumi Shiina", image: "Yumi_S_silhouette", opus: ["P5X"] },
{ nom: "Chizuko Nagao", image: "Chizuko_silhouette", opus: ["P5X"] },


 // === Persona 1 ===
  { nom: "Naoya Todou", image: "Naoya_Toudou_silhouette", opus: ["P1"] },
  { nom: "Maki Sonomura", image: "Maki_Sonomura_silhouette", opus: ["P1"] },
  { nom: "Masao Inaba", image: "Masao_Inaba_silhouette", opus: ["P1"] },
  { nom: "Kei Nanjo", image: "Kei_Nanjo_silhouette", opus: ["P1"] },
  { nom: "Yukino Mayuzumi", image: "Yukino_Mayuzumi_silhouette", opus: ["P1"] },
  { nom: "Hidehiko Uesugi", image: "Hidehiko_Uesugi_silhouette", opus: ["P1"] },
  { nom: "Eriko Kirishima", image: "Eriko_Kirishima_silhouette", opus: ["P1"] },
  { nom: "Yuka Ayase", image: "Yuka_Ayase_silhouette", opus: ["P1"] },
  { nom: "Reiji Kido", image: "Reiji_Kido_silhouette", opus: ["P1"] },

  // === Persona 2 ===
  { nom: "Tatsuya Suou", image: "Tatsuya_Suou_silhouette", opus: ["P2IS", "P2EP"] },
  { nom: "Maya Amano", image: "Maya_Amano_silhouette", opus: ["P2IS", "P2EP"] },
  { nom: "Lisa Silverman", image: "Lisa_Silverman_silhouette", opus: ["P2IS"] },
  { nom: "Jun Kurosu", image: "Jun_Kurosu_silhouette", opus: ["P2IS"] },
  { nom: "Eikichi Mishina", image: "Eikichi_Mishina_silhouette", opus: ["P2IS"] },
  { nom: "Baofu", image: "Baofu_silhouette", opus: ["P2EP"] },
  { nom: "Joker", image: "Joker_silhouette", opus: ["P2IS"] }



  
]; 