/**
 * A list of persona names used for text autocompletion.
 */
export const personas = [
  "Aigis",
  "Aigis ( P3FES )",
  "Akihiko Sanada",
  "Ange ( Manaka Nagao )",
  "Berry ( Ichigo Shikano )",
  "Black Mask ( Goro Akechi )",
  "Bui ( YUI )",
  "Caroline & Justine",
  "Cattle ( Lufel )",
  "Cherish ( Masaki Ashiya )",
  "Chord ( Ayaka Sakai )",
  "Chord Summer ( Ayaka Sakai )",
  "Closer ( Motoha Arai )",
  "Closer Summer ( Motoha Arai )",
  "Crow ( Goro Akechi )",
  "Fleuret ( Seiji Shiratori )",
  "Fox ( Yusuke Kitagawa )",
  "Fuuka Yamagishi",
  "Howler ( Runa Dogenzaka )",
  "Joker ( Ren Amamiya )",
  "Joker Starlight ( Ren Amamiya )",
  "Junpei Iori",
  "Ken Amada",
  "Key ( Kiyoshi Kurotani )",
  "Koromaru",
  "Kotone Shiomi",
  "Lavenza",
  "Leon ( Leo Kamiyama )",
  "Luce ( Shoki Ikenami )",
  "Makoto Yuki",
  "Marian ( Minami Miyashita )",
  "Matoi ( Mio Natsukawa )",
  "Metis",
  "Messa ( Kira Kitazato )",
  "Mitsuru Kirijo",
  "Moko ( Tomoko Noge )",
  "Moko Summer ( Tomoko Noge )",
  "Mont ( Kotone Montagne )",
  "Mona ( Morgana )",
  "Noir ( Haru Okumura )",
  "Okyann ( Kayo Tomiyama )",
  "Oracle ( Futaba Sakura )",
  "Panther ( Ann Takamaki )",
  "Phoebe ( Yumi S. )",
  "Puppet ( Miyu Sahara )",
  "Queen ( Makoto Niijima )",
  "Riddle ( Haruna Nishimori )",
  "Rin ( Yaoling Li )",
  "Rin Chinese New Year ( Yaoling Li )",
  "Sepia ( Toshiya Sumi )",
  "Shinjiro Aragaki",
  "Skull ( Ryuji Sakamoto )",
  "Soy ( Shun Kano )",
  "Turbo ( Mayumi Hashimoto )",
  "Violet ( Sumire Yoshizawa )",
  "Vino ( Chizuko Nagao )",
  "Wind ( Riko Tanemura )",
  "Wonder ( Nagisa Kamishiro )",
  "Wonder Chinese New Year ( Nagisa Kamishiro )",
  "Wonder Velvet ( Nagisa Kamishiro )",
  "Wonder Summer ( Nagisa Kamishiro )",
  "Yuki ( Yukimi Fujikawa )",
  "Yukari Takeba",
  "Anri ( Aran Hirano )",
  "Pinky ( Narumi Nashimoto )",
  "Blitz ( Kumi Katayama )",
  "Mona Starlight ( Morgana )",
  "Panther Starlight ( Ann Takamaki )",
  "Marian Summer ( Minami Miyashita )",
  "Puppet Summer ( Miyu Sahara )",
  "Closer Radiance ( Motoha Arai )",
  "Miku ( Hatsune Miku )",
];
