/**
 * A list of persona names used for text autocompletion.
 */
export const personas = [
  "Aigis",
  "Aigis ( P3FES )",
  "Akihiko Sanada",
  "Ange ( Manaka Nagao )",
  "Berry ( Ichigo Shikano )",
  "Black Mask ( Goro Akechi )",
  "Bui ( YUI )",
  "Caroline & Justine",
  "Cattle ( Lufel )",
  "Cherish ( Masaki Ashiya )",
  "Chord ( Ayaka Sakai )",
  "Closer ( Motoha Arai )",
  "Crow ( Goro Akechi )",
  "Fleuret ( Ayaka Sakai )",
  "Fox ( Yusuke Kitagawa )",
  "Howler ( Runa Dogenzaka )",
  "Joker ( Ren Amamiya )",
  "Junpei Iori",
  "Ken Amada",
  "Key ( Kiyoshi Kurotani )",
  "Koromaru",
  "Kotone Shiomi",
  "Lavenza",
  "Leon ( Leo Kamiyama )",
  "Luce ( Shoki Ikenami )",
  "Makoto Yuki",
  "Marian ( Minami Miyashita )",
  "Matoi ( Mio Natsukawa )",
  "Metis",
  "Messa ( Kira Kitazato )",
  "Mitsuru Kirijo",
  "Moko ( Tomoko Noge )",
  "Mont ( Kotone Montagne )",
  "Mona ( Morgana )",
  "Noir ( Haru Okumura )",
  "Okyann ( Kayo Tomiyama )",
  "Oracle ( Futaba Sakura )",
  "Panther ( Ann Takamaki )",
  "Phoebe ( Yumi S. )",
  "Puppet ( Miyu Sahara )",
  "Queen ( Makoto Niijima )",
  "Riddle ( Haruna Nishimori )",
  "Rin ( Yaoling Li )",
  "Sepia ( Toshiya Sumi )",
  "Shinjiro Aragaki",
  "Skull ( Ryuji Sakamoto )",
  "Soy ( Shun Kano )",
  "Turbo ( Mayumi Hashimoto )",
  "Violet ( Sumire Yoshizawa )",
  "Vino ( Chizuko Nagao )",
  "Wind ( Riko Tanemura )",
  "Wonder ( Nagisa Kamishiro )",
  "Yuki ( Yukimi Fujikawa )",
  "Yukari Takeba"
];
