/**
 * A list of persona names used for text autocompletion.
 */
export const personas = [
  "Aigis",
  "Aigis ( P3FES )",
  "Akihiko Sanada",
  "Panther ( Ann Takamaki )",
  "Caroline & Justine",
  "Oracle ( Futaba Sakura )",
  "Crow ( Goro Akechi )",
  "Black Mask ( Goro Akechi )",
  "Noir ( Haru Okumura )",
  "Junpei Iori",
  "Ken Amada",
  "Kotone Shiomi",
  "Koromaru",
  "Lavenza",
  "Makoto Yuki",
  "Queen ( Makoto Niijima )",
  "Metis",
  "Mitsuru Kirijo",
  "Mona ( Morgana )",
  "Joker ( Ren Amamiya )",
  "Skull ( Ryuji Sakamoto )",
  "Shinjiro Aragaki",
  "Violet ( Sumire Yoshizawa )",
  "Yukari Takeba",
  "Fox ( Yusuke Kitagawa )",
];
