/**
 * A mapping between persona display names and their corresponding portrait identifiers.
 * Used to ensure accurate image linking in autocompletion components.
 */
export const portraitsMap = {
  // P3
  "Aigis": "Aigis",
  "Akihiko Sanada": "Akihiko",
  "Junpei Iori": "Junpei",
  "Ken Amada": "Ken",
  "Kotone Shiomi": "Kotone",
  "Koromaru": "Koromaru",
  "Lavenza": "Lavenza",
  "Makoto Yuki": "Yuki",
  "Mitsuru Kirijo": "Mitsuru",
  "Shinjiro Aragaki": "Shinjiro",
  "Yukari Takeba": "Yukari",
  "Metis": "Metis",
  "Aigis ( P3FES )": "Aigis_FES",
  "Fuuka Yamagishi": "Fuuka",

  // P5 - alias comme nom d’image
  "Panther ( Ann Takamaki )": "Panther",
  "Queen ( Makoto Niijima )": "Queen",
  "Fox ( Yusuke Kitagawa )": "Fox",
  "Noir ( Haru Okumura )": "Noir",
  "Oracle ( Futaba Sakura )": "Oracle",
  "Mona ( Morgana )": "Mona",
  "Joker ( Ren Amamiya )": "Joker",
  "Joker Starlight ( Ren Amamiya )": "Joker_Starlight",
  "Skull ( Ryuji Sakamoto )": "Skull",
  "Violet ( Sumire Yoshizawa )": "Violet",
  "Crow ( Goro Akechi )": "Crow",
  "Black Mask ( Goro Akechi )": "Black_mask",

  // Velvet Room
  "Caroline & Justine": "Caroline_and_Justine",

  // P5X
  "Wonder ( Nagisa Kamishiro )": "Wonder",
  "Wonder Chinese New Year ( Nagisa Kamishiro )": "Wonder_ChineseNY",
  "Wonder Velvet ( Nagisa Kamishiro )": "Wonder_Velvet",
  "Wonder Summer ( Nagisa Kamishiro )": "Wonder_Summer",
  "Closer ( Motoha Arai )": "Closer",
  "Closer Summer ( Motoha Arai )": "Closer_Summer",
  "Fleuret ( Seiji Shiratori )": "Fleuret",
  "Leon ( Leo Kamiyama )": "Leon",
  "Rin ( Yaoling Li )": "Rin",
  "Rin Chinese New Year ( Yaoling Li )": "Rin_ChineseNY",
  "Wind ( Riko Tanemura )": "Wind",
  "Soy ( Shun Kano )": "Soy",
  "Moko ( Tomoko Noge )": "Moko",
  "Moko Summer ( Tomoko Noge )": "Moko_Summer",
  "Sepia ( Toshiya Sumi )": "Sepia",
  "Key ( Kiyoshi Kurotani )": "Key",
  "Okyann ( Kayo Tomiyama )": "Okyann",
  "Puppet ( Miyu Sahara )": "Puppet",
  "Riddle ( Haruna Nishimori )": "Riddle",
  "Yuki ( Yukimi Fujikawa )": "YukiX",
  "Mont ( Kotone Montagne )": "Mont",
  "Chord ( Ayaka Sakai )": "Chord",
  "Messa ( Kira Kitazato )": "Messa",
  "Cherish ( Masaki Ashiya )": "Cherish",
  "Howler ( Runa Dogenzaka )": "Howler",
  "Matoi ( Mio Natsukawa )": "Matoi",
  "Turbo ( Mayumi Hashimoto )": "Turbo",
  "Ange ( Manaka Nagao )": "Ange",
  "Phoebe ( Yumi S. )": "Phoebe",
  "Cattle ( Lufel )": "Cattle",
  "Bui ( YUI )": "Bui",
  "Marian ( Minami Miyashita )": "Marian",
  "Vino ( Chizuko Nagao )": "Vino",
  "Luce ( Shoki Ikenami )": "Luce",
  "Berry ( Ichigo Shikano )": "Berry",
  // P5X — nouveaux Phantom Idols + skins
  "Anri ( Aran Hirano )": "Anri",
  "Pinky ( Narumi Nashimoto )": "Pinky",
  "Blitz ( Kumi Katayama )": "Blitz",
  "Mona Starlight ( Morgana )": "Mona_Starlight",
  "Marian Summer ( Minami Miyashita )": "Marian_Summer",
  "Puppet Summer ( Miyu Sahara )": "Puppet_Summer",
  "Closer Radiance ( Motoha Arai )": "Closer_Radiance",
  "Miku ( Hatsune Miku )": "Miku",
};
