export const characters = [  {
    nom: "Yu Narukami",
    genre: "Male",
    age: 17,
    arcane: ["Fool", "Judgment", "World"],
    opus: "P4",
    personaUser: true,
    persona: "Izanagi",
    emoji: "🗡️⚡😐",
    quote: "People can do it. As long as they open their eyes and look around, they'll see it..."
  },
  {
    nom: "Ai Ebihara",
    genre: "Female",
    age: 16,
    arcane: ["Moon"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "💅💔😤",
    quote: "I've carried that thing around ever since I decided to change who I was..."
  },
  {
    nom: "Ayane Matsunaga",
    genre: "Female",
    age: 15,
    arcane: ["Sun"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "🎺😖🌱",
    quote: "I've been keeping a lot of... unpleasant emotions buried inside..."
  },
  {
    nom: "Chie Satonaka",
    genre: "Female",
    age: 17,
    arcane: ["Chariot"],
    opus: "P4",
    personaUser: true,
    persona: "Tomoe",
    emoji: "🥋🍖🤩",
    quote: "...I think this \"power\" of mine is what I wanted all along..."
  },
  {
    nom: "Daisuke Nagase",
    genre: "Male",
    age: 17,
    arcane: ["Strength"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "⚽💪😅",
    quote: "I kept pretending that I was trying my hardest..."
  },
  {
    nom: "Eri Minami",
    genre: "Female",
    age: 30,
    arcane: ["Temperance"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "👩‍👦📖😔",
    quote: "I wasn't even trying to see him for myself. Maybe I was just afraid..."
  },
  {
    nom: "Fox",
    genre: "Animal",
    age: "Unknown",
    arcane: ["Hermit"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "🦊🎴🙏",
    quote: "*Yip*"
  },
  {
    nom: "Hisano Kuroda",
    genre: "Female",
    age: 70,
    arcane: ["Death"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "💔👵💀",
    quote: "Live a long and full life. That is the greatest thing you can do..."
  },
  {
    nom: "Kanji Tatsumi",
    genre: "Male",
    age: 16,
    arcane: ["Emperor"],
    opus: "P4",
    personaUser: true,
    persona: "Take-Mikazuchi",
    emoji: "🧵💢🚴‍♂️",
    quote: "I get it now... This is what he was talking about..."
  },
  {
    nom: "Kou Ichijo",
    genre: "Male",
    age: 17,
    arcane: ["Strength"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "🏀😎🎭",
    quote: "I thought I had it all figured out, but I just didn't get it..."
  },
  {
    nom: "Margaret",
    genre: "Female",
    age: "Unknown",
    arcane: ["Empress"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "📖✨😏",
    quote: "Truth is a thing which only appears to those who have observed..."
  },
  {
    nom: "Marie",
    genre: "Female",
    age: 16,
    arcane: ["Aeon"],
    opus: "P4G",
    personaUser: false,
    persona: "NONE",
    emoji: "📝🌧️💚",
    quote: "There are things that you can't do by yourself, but can do with others..."
  },
  {
    nom: "Nanako Dojima",
    genre: "Female",
    age: 6,
    arcane: ["Justice"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "🧃🎶😊",
    quote: "Every day's great at your Junes!"
  },
  {
    nom: "Naoki Konishi",
    genre: "Male",
    age: 16,
    arcane: ["Hanged Man"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "🛒😞🪄",
    quote: "There's a river separating us... Sis is gone, and I'm still here..."
  },
  {
    nom: "Ryotaro Dojima",
    genre: "Male",
    age: 42,
    arcane: ["Hierophant"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "🚬🕵️‍♂️😓",
    quote: "This town is my town. It's the place where you and Nanako live..."
  },
  {
    nom: "Sayako Uehara",
    genre: "Female",
    age: 28,
    arcane: ["Devil"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "🏥🍶😏",
    quote: "So... I'm going. I'm going to find that path I gave up on..."
  },
  {
    nom: "Shu Nakajima",
    genre: "Male",
    age: 13,
    arcane: ["Tower"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "📚🎓😠",
    quote: "I'm going to be my own guide. Thinking, walking, taking responsibility for myself..."
  },
  {
    nom: "Yumi Ozawa",
    genre: "Female",
    age: 16,
    arcane: ["Sun"],
    opus: "P4",
    personaUser: false,
    persona: "NONE",
    emoji: "🎭💔😭",
    quote: "Dad... Thank you for bringing me... into this world..."
  },
  {
    nom: "Naoto Shirogane",
    genre: "Female",
    age: 16,
    arcane: ["Fortune"],
    opus: "P4",
    personaUser: true,
    persona: "Sukuna-Hikona",
    emoji: "🔍🕵️‍♂️🔫",
    quote: "The title of detective became a burden to me... I thought I had no other aspects apart from detective self. But you and the others gave me a reason to be, as neither adult nor man... So, I... I was able to face myself as myself. Before the detective, before the child, before the woman. By spending time with you all, I change, day by day. It frightened me before... But now... With everyone... With you, I can proudly proclaim that I am myself. Nothing more, but nothing less."
  },
  {
    nom: "Rise Kujikawa",
    genre: "Female",
    age: 16,
    arcane: ["Lovers"],
    opus: "P4",
    personaUser: true,
    persona: "Himiko",
    emoji: "🎤💕😜",
    quote: "Senpai... I won't make the same mistake. There's no such thing as a me who isn't me. So I won't run away... I won't try to be someone I'm not. There's a lot of Rises inside me... I won't try to change them. Instead... I'll let people know that those Rises exist... That's the me I want to be."
  },
  {
    nom: "Teddie",
    genre: "Animal",
    age: "Unknown",
    arcane: ["Star"],
    opus: "P4",
    personaUser: true,
    persona: "Kintoki-Douji",
    emoji: "🧸❄️🤣",
    quote: "Doesn't matter how far apart we are. The bonds we've made will remain strong. Everyone's hearts is connected to the people they know and trust. It's those bonds that let us all search for our purpose in life. As long as it's a purpose that you believe in, there will always be someone who could help you fulfill it. You, me, and everyone else, there are no barriers. Our hearts are one. Right, Sensei?"
  },
  {
    nom: "Tohru Adachi",
    genre: "Male",
    age: 27,
    arcane: ["Hunger", "Jester"],
    opus: "P4G",
    personaUser: true,
    persona: "Magatsu-Izanagi",
    emoji: "🍆🔫😈",
    quote: "Let's be honest. There's nothing great about the real world, is there? It's just dull and annoying as hell. No one accepts that's the way things are... They're just stuck with it because they can't deny it, either. Those who actually succeed in life... They just happen to be born with the magic ticket called talent. If you don't have it, you can either accept or deny that fact until you die. That's your only choice. Once you realize that, all you have left in life is despair. The ultimate game over. Wouldn't it be better if that kind of reality was wiped away?"
  },
  {
    nom: "Yosuke Hanamura",
    genre: "Male",
    age: 17,
    arcane: ["Magician"],
    opus: "P4",
    personaUser: true,
    persona: "Jiraya",
    emoji: "🎧🚲😂",
    quote: "Is Saki-senpai watching us...? Is she smiling at us? Senpai... I'm going to live. Without lying to myself, without deceiving myself... Days like today, days like before when I did nothing... They're all important days... They're all days you didn't live to see... I'm going to live them here."
  },
  {
    nom: "Yukiko Amagi",
    genre: "Female",
    age: 17,
    arcane: ["Priestess"],
    opus: "P4",
    personaUser: true,
    persona: "Konohana Sakuya",
    emoji: "🏯🔥😳",
    quote: "I wanted to become completely self-sufficient. But I think I was being presumptuous. I have the inn, I have my family, I have the waitresses and chefs... I am who I am now because I was raised by such a kind group... When I think of it that way, my problems aren't just my own. That's why... I'm going to stay here. By my own will."
  },
];


