/**
 * A list of persona names used for text autocompletion.
 */
export const personas = [
  "Aigis",
  "Ai Ebihara",
  "Akinari Kamiki",
  "Akihiko Sanada",
  "Ann Takamaki",
  "Ayane Matsunaga",
  "Bebe",
  "Bunkichi",
  "Caroline",
  "Chie Satonaka",
  "Chihaya Mifune",
  "Chihiro Fushimi",
  "Daisuke Nagase",
  "Eri Minami",
  "Elizabeth",
  "Fox",
  "Fuuka Yamagishi",
  "Futaba Sakura",
  "Goro Akechi",
  "Haru Okumura",
  "Hidetoshi Odagiri",
  "Hifumi Togo",
  "Hisano Kuroda",
  "Ichiko Ohya",
  "Igor",
  "Junpei Iori",
  "Justine",
  "Kanji Tatsumi",
  "Kasumi Yoshizawa",
  "Kazushi Miyamoto",
  "Keisuke Hiraga",
  "Ken Amada",
  "Kenji Tomochika",
  "Kou Ichijo",
  "Kotone Shiomi",
  "Koromaru",
  "Lavenza",
  "Makoto Yuki",
  "Makoto Niijima",
  "Margaret",
  "Marie",
  "Maiko Oohashi",
  "Mamoru Hayase",
  "Maya",
  "Mitsuko",
  "Mitsuru Kirijo",
  "Morgana",
  "Munehisa Iwai",
  "Mutatsu",
  "Nanako Dojima",
  "Naoki Konishi",
  "Naoto Shirogane",
  "Nozomi Suemitsu",
  "Pharos",
  "President Tanaka",
  "Ren Amamiya",
  "Rise Kujikawa",
  "Ryoji Mochizuki",
  "Ryotaro Dojima",
  "Ryuji Sakamoto",
  "Rio Iwasaki",
  "Sadayo Kawakami",
  "Saori Hasegawa",
  "Sae Niijima",
  "Sayako Uehara",
  "Sojiro Sakura",
  "Shinya Oda",
  "Shu Nakajima",
  "Shinjiro Aragaki",
  "Sumire Yoshizawa",
  "Takuto Maruki",
  "Tae Takemi", 
  "Teddie",
  "Theodore",
  "Tohru Adachi",
  "Toranosuke Yoshida",
  "Yosuke Hanamura",
  "Yu Narukami",
  "Yukari Takeba",
  "Yukiko Amagi",
  "Yumi Ozawa",
  "Yuko Nishiwaki",
  "Yusuke Kitagawa",
  "Yuuki Mishima",
  "Kinshiro Morooka",
  "Noriko Kashiwagi",
  "Hanako Ohtani",
  "Mitsuo Kubo",
  "Mr. Edogawa",
  "Jose",
  "Metis",
  "Sho Minazuki",
  "Labrys",
  "Suguru Kamoshida",
  "Ichiryusai Madarame",
  "Junya Kaneshiro",
  "Jin Shirato",
  "Shuji Ikutsuki",
  "Chidori Yoshino",
  "Takaya Sakaki",
  "Hatsune Miku",
 "Naoya Todou",
  "Maki Sonomura",
  "Masao Inaba",
  "Kei Nanjo",
  "Yukino Mayuzumi",
  "Hidehiko Uesugi",
  "Eriko Kirishima",
  "Yuka Ayase",
  "Reiji Kido",
  "Tatsuya Suou",
  "Maya Amano",
  "Lisa Silverman",
  "Jun Kurosu",
  "Eikichi Mishina",
  "Baofu",
  "Joker",
  "Sophia",
  "Zenkichi Hasegawa",
  "Kunikazu Okumura",
  "Masayoshi Shido",
    "Nagisa Kamishiro",
  "Lufel",
  "Motoha Arai",
  "Shun Kano",
  "Riko Tanemura",
  "Shoki Ikenami",
  "Seiji Shiratori",
  "Kotone Montagne",
  "Yukimi Fujikawa",
  "Tomoko Noge",
  "Leo Kamiyama",
  "Yaoling Li",
  "Kiyoshi Kurotani",
  "Kayo Tomiyama",
  "Miyu Sahara",
  "Toshiya Sumi",
  "Haruna Nishimori",
  "YUI",
  "Minami Miyashita",
  "Chizuko Nagao",
  "Yumi Shiina",
  "Ayaka Sakai",
  "Kira Kitazato",
  "Masaki Ashiya",
  "Runa Dogenzaka",
  "Mio Natsukawa",
  "Mayumi Hashimoto",
  "Manaka Nagao",
  "Ichigo Shikano",
  "Merope"


];
