/**
 * A list of persona names used for text autocompletion.
 */
export const personas = [
  "Aigis",
  "Ai Ebihara",
  "Akinari Kamiki",
  "Akihiko Sanada",
  "Ann Takamaki",
  "Ayane Matsunaga",
  "Bebe",
  "Bunkichi",
  "Caroline",
  "Chie Satonaka",
  "Chihaya Mifune",
  "Chihiro Fushimi",
  "Daisuke Nagase",
  "Eri Minami",
  "Elizabeth",
  "Fox",
  "Fuuka Yamagishi",
  "Futaba Sakura",
  "Goro Akechi",
  "Haru Okumura",
  "Hidetoshi Odagiri",
  "Hifumi Togo",
  "Hisano Kuroda",
  "Ichiko Ohya",
  "Igor",
  "Junpei Iori",
  "Justine",
  "Kanji Tatsumi",
  "Kasumi Yoshizawa",
  "Kazushi Miyamoto",
  "Keisuke Hiraga",
  "Ken Amada",
  "Kenji Tomochika",
  "Kou Ichijo",
  "Kotone Shiomi",
  "Koromaru",
  "Lavenza",
  "Makoto Yuki",
  "Makoto Niijima",
  "Margaret",
  "Marie",
  "Maiko Oohashi",
  "Mamoru Hayase",
  "Maya",
  "Mitsuko",
  "Mitsuru Kirijo",
  "Morgana",
  "Munehisa Iwai",
  "Mutatsu",
  "Nanako Dojima",
  "Naoki Konishi",
  "Naoto Shirogane",
  "Nozomi Suemitsu",
  "Pharos",
  "President Tanaka",
  "Ren Amamiya",
  "Ryoji Mochizuki",
  "Ryotaro Dojima",
  "Ryuji Sakamoto",
  "Rio Iwasaki",
  "Sadayo Kawakami",
  "Saori Hasegawa",
  "Sae Niijima",
  "Sayako Uehara",
  "Sojiro Sakura",
  "Shinya Oda",
  "Shu Nakajima",
  "Shinjiro Aragaki",
  "Sumire Yoshizawa",
  "Takuto Maruki",
  "Tae Takemi", 
  "Teddie",
  "Theodore",
  "Tohru Adachi",
  "Toranosuke Yoshida",
  "Yosuke Hanamura",
  "Yu Narukami",
  "Yukari Takeba",
  "Yukiko Amagi",
  "Yumi Ozawa",
  "Yusuke Kitagawa",
  "Yuuki Mishima",
  "Kinshiro Morooka",
  "Noriko Kashiwagi",
  "Hanako Ohtani",
  "Mitsuo Kubo",
  "Mr. Edogawa",
  "Jose"
];
