/**
 * A mapping between character names and their corresponding portrait identifiers.
 * This object is used to link autocompletion inputs to the appropriate portrait images.
 */
export const portraitsMap = {
  "Ai Ebihara": "Ai",
  "Ayane Matsunaga": "Ayane",
  "Chie Satonaka": "Chie",
  "Daisuke Nagase": "Daisuke",
  "Eri Minami": "Eri",
  "Fox": "Fox",
  "Hisano Kuroda": "Hisano",
  "Kanji Tatsumi": "Kanji",
  "Kou Ichijo": "Kou",
  "Margaret": "Margaret",
  "Marie": "Marie",
  "Nanako Dojima": "Nanako",
  "Naoki Konishi": "Naoki",
  "Naoto Shirogane": "Naoto",
  "Rise Kujikawa": "Rise",
  "Ryotaro Dojima": "Dojima",
  "Sayako Uehara": "Sayako",
  "Shu Nakajima": "Shu",
  "Teddie": "Teddie",
  "Tohru Adachi": "Tohru",
  "Yosuke Hanamura": "Yosuke",
  "Yu Narukami": "Yu",
  "Yumi Ozawa": "Yumi",
  "Yukiko Amagi":"Yukiko",
  "Munehisa Iwai": "Iwai",
  "Mamoru Hayase": "Hayase",
  "Ichiko Ohya": "Ohya",
  "Makoto Yuki": "Yuki",
  "President Tanaka": "Tanaka",
   "Sadayo Kawakami": "Kawakami",
   "Shinya Oda": "Oda",
   "Toranosuke Yoshida": "Yoshida",
   "Sumire Yoshizawa": "Sumire",
   "Takuto Maruki": "Maruki",
   "Tae Takemi": "Takemi",
   "Yuuki Mishima": "Mishima",
   "Makoto Niijima": "Makoto",
   "Kinshiro Morooka": "Morooka",
   "Mr. Edogawa": "Edgoawa",
   "Ichiryusai Madarame": "Madarame",
   "Hatsune Miku": "Miku",
   "Shuji Ikutsuki": "Ikutsuki",

    "Naoya Todou": "Naoya",
   "Maki Sonomura": "Maki",
   "Joker": "JOKER",
   "Baofu": "Baofu",
   "Eikichi Mishina": "Eikichi",
   "Jun Kurosu": "Jun",
   "Lisa Silverman": "Lisa",
   "Maya Amano": "Maya_A",
   "Tatsuya Suou": "Tatsuya",
   "Motoha Arai": "Arai",
  "Kotone Montagne": "Montagne",
  "Leo Kamiyama": "Reo",
  "Yumi Shiina": "Yumi_S",
  "Taro Namatame": "Namatame",
"Izanami": "Izanami",
};
