/**
 * A mapping between character names and their corresponding portrait identifiers.
 * This object is used to link autocompletion inputs to the appropriate portrait images.
 */
export const portraitsMap = {

  // ── Persona 1 ──────────────────────────────────────────────────────────────
  "Naoya Todou":       "Naoya",
  "Maki Sonomura":     "Maki",
  "Masao Inaba":       "Masao",
  "Kei Nanjo":         "Kei",
  "Yukino Mayuzumi":   "Yukino",
  "Hidehiko Uesugi":   "Hidehiko",
  "Eriko Kirishima":   "Eriko",
  "Yuka Ayase":        "Yuka",
  "Reiji Kido":        "Reiji",
  "Philemon":          "Philemon",
  "Nameless":          "Nameless",
  "Belladonna":        "Belladonna",

  // ── Persona 2 ──────────────────────────────────────────────────────────────
  "Tatsuya Suou":      "Tatsuya",
  "Lisa Silverman":    "Lisa",
  "Eikichi Mishina":   "Eikichi",
  "Maya Amano":        "Maya_A",
  "Jun Kurosu":        "Jun",
  "Ulala Serizawa":    "Ulala",
  "Katsuya Suou":      "Katsuya",
  "Baofu":             "Baofu",

  // ── Persona 3 ──────────────────────────────────────────────────────────────
  "Makoto Yuki":       "Yuki",
  "Kotone Shiomi":     "Kotone",
  "Junpei Iori":       "Junpei",
  "Yukari Takeba":     "Yukari",
  "Fuuka Yamagishi":   "Fuuka",
  "Mitsuru Kirijo":    "Mitsuru",
  "Akihiko Sanada":    "Akihiko",
  "Aigis":             "Aigis",
  "Ken Amada":         "Ken",
  "Koromaru":          "Koromaru",
  "Shinjiro Aragaki":  "Shinjiro",
  "Metis":             "Metis",
  "Ryoji Mochizuki":   "Ryoji",
  "Pharos":            "Pharos",
  "Takaya Sakaki":     "Takaya",
  "Jin Shirato":       "Jin",
  "Chidori Yoshino":   "Chidori",
  "Elizabeth":         "Elizabeth",
  "Theodore":          "Theodore",
  "Kenji Tomochika":   "Kenji",
  "Hidetoshi Odagiri": "Hidetoshi",
  "Bunkichi":          "Bunkichi",
  "Mitsuko":           "Mitsuko",
  "Kazushi Miyamoto":  "Kazushi",
  "Rio Iwasaki":       "Rio",
  "Chihiro Fushimi":   "Chihiro",
  "Maya":              "Maya",
  "Saori Hasegawa":    "Saori",
  "Keisuke Hiraga":    "Keisuke",
  "Yuko Nishiwaki":    "Yuko",
  "Maiko Oohashi":     "Maiko",
  "Bebe":              "Bebe",
  "Mutatsu":           "Mutatsu",
  "Nozomi Suemitsu":   "Nozomi",
  "Akinari Kamiki":    "Akinari",
  "Shuji Ikutsuki":    "Ikutsuki",

  // ── Persona 4 ──────────────────────────────────────────────────────────────
  "Yu Narukami":       "Yu",
  "Yosuke Hanamura":   "Yosuke",
  "Chie Satonaka":     "Chie",
  "Yukiko Amagi":      "Yukiko",
  "Kanji Tatsumi":     "Kanji",
  "Rise Kujikawa":     "Rise",
  "Naoto Shirogane":   "Naoto",
  "Teddie":            "Teddie",
  "Marie":             "Marie",
  "Margaret":          "Margaret",
  "Ryotaro Dojima":    "Dojima",
  "Nanako Dojima":     "Nanako",
  "Tohru Adachi":      "Tohru",
  "Taro Namatame":     "Namatame",
  "Izanami":           "Izanami",
  "Noriko Kashiwagi":  "Noriko",
  "Hanako Ohtani":     "Hanako",
  "Mitsuo Kubo":       "Mitsuo",
  "Ai Ebihara":        "Ai",
  "Kou Ichijo":        "Kou",
  "Daisuke Nagase":    "Daisuke",
  "Yumi Ozawa":        "Yumi",
  "Ayane Matsunaga":   "Ayane",
  "Naoki Konishi":     "Naoki",
  "Saki Konishi":      "Saki",
  "Mayumi Yamano":     "Mayumi",
  "Hisano Kuroda":     "Hisano",
  "Shu Nakajima":      "Shu",
  "Sayako Uehara":     "Sayako",
  "Fox":               "Fox",
  "Eri Minami":        "Eri",

  // ── Persona 4 Arena / Ultimax ───────────────────────────────────────────────
  "Labrys":            "Labrys",
  "Sho Minazuki":      "Sho",

  // ── Persona Q ─────────────────────────────────────────────────────────────
  "Rei":               "Rei",
  "Zen":               "Zen",

  // ── Persona Q2 ────────────────────────────────────────────────────────────
  "Hikari":            "Hikari",
  "Nagi":              "Nagi",

  // ── Persona 5 ─────────────────────────────────────────────────────────────
  "Joker":             "JOKER",
  "Ren Amamiya":       "Ren",
  "Morgana":           "Morgana",
  "Ryuji Sakamoto":    "Ryuji",
  "Ann Takamaki":      "Ann",
  "Yusuke Kitagawa":   "Yusuke",
  "Makoto Niijima":    "Makoto",
  "Futaba Sakura":     "Futaba",
  "Haru Okumura":      "Haru",
  "Goro Akechi":       "Goro",
  "Sumire Yoshizawa":  "Sumire",
  "Kasumi Yoshizawa":  "Kasumi",
  "Sae Niijima":       "Sae",
  "Kobayakawa":        "Kobayakawa",
  "Wakaba Isshiki":    "Wakaba_Isshiki",
  "Sojiro Sakura":     "Sojiro",
  "Chihaya Mifune":    "Chihaya",
  "Hifumi Togo":       "Hifumi",
  "Ichiko Ohya":       "Ohya",
  "Munehisa Iwai":     "Iwai",
  "Sadayo Kawakami":   "Kawakami",
  "Tae Takemi":        "Takemi",
  "Toranosuke Yoshida":"Yoshida",
  "Shinya Oda":        "Oda",
  "Yuuki Mishima":     "Mishima",
  "President Tanaka":  "Tanaka",
  "Mamoru Hayase":     "Hayase",
  "Hatsune Miku":      "Miku",
  "Mr. Edogawa":       "Edgoawa",
  "Suguru Kamoshida":  "Suguru",
  "Ichiryusai Madarame":"Madarame",
  "Junya Kaneshiro":   "Junya",
  "Kunikazu Okumura":  "Kunikazu",
  "Masayoshi Shido":   "Masayoshi",
  "Caroline":          "Caroline",
  "Justine":           "Justine",
  "Lavenza":           "Lavenza",
  "Jose":              "Jose",
  "Takuto Maruki":     "Maruki",
  "Kinshiro Morooka":  "Morooka",

  // ── Persona 5 Strikers ────────────────────────────────────────────────────
  "Sophia":            "Sophia",
  "Zenkichi Hasegawa": "Zenkichi",
  "Akane Hasegawa":    "Akane_Hasegawa",
  "Kuon Ichinose":     "Kuon_Ichinose",
  "Alice Hiiragi":     "Alice_Hiiragi",
  "Ango Natsume":      "Ango_Natsume",
  "Mariko Hyodo":      "Mariko_Hyodo",
  "Akira Konoe":       "Akira_Konoe",

  // ── Persona 5 Tactica ────────────────────────────────────────────────────
  "Erina":             "Erina",
  "Toshiro Kasukabe":  "Toshiro",

  // ── Persona 5 The Royal (Scramble DLC) ───────────────────────────────────
  "Motoha Arai":       "Arai",

  // ── Persona 5X ────────────────────────────────────────────────────────────
  "Nagisa Kamishiro":  "Nagisa",
  "Lufel":             "Lufel",
  "Shun Kano":         "Shun",
  "Riko Tanemura":     "Riko",
  "Shoki Ikenami":     "Shoki",
  "Seiji Shiratori":   "Seiji",
  "Aran Hirano":       "Aran",
  "Narumi Nashimoto":  "Narumi",
  "Kumi Katayama":     "Kumi_Katayama",
  "Yukimi Fujikawa":   "Yukimi",
  "Tomoko Noge":       "Tomoko",
  "Yaoling Li":        "Yaoling",
  "Kiyoshi Kurotani":  "Kiyoshi",
  "Kayo Tomiyama":     "Kayo",
  "Miyu Sahara":       "Miyu",
  "Toshiya Sumi":      "Toshiya",
  "Haruna Nishimori":  "Haruna",
  "YUI":               "YUI",
  "Minami Miyashita":  "Minami",
  "Chizuko Nagao":     "Chizuko",
  "Ayaka Sakai":       "Ayaka",
  "Kira Kitazato":     "Kira",
  "Masaki Ashiya":     "Masaki",
  "Runa Dogenzaka":    "Runa",
  "Mio Natsukawa":     "Mio",
  "Mayumi Hashimoto":  "Mayumi",
  "Manaka Nagao":      "Manaka",
  "Ichigo Shikano":    "Ichigo",
  "Kotone Montagne":   "Montagne",
  "Leo Kamiyama":      "Reo",
  "Yumi Shiina":       "Yumi_S",

  // ── Entités / Boss finaux ─────────────────────────────────────────────────
  "Igor":              "Igor",
  "Nyx":               "Nyx",
  "Ameno-sagiri":      "Amenosagiri",
  "Yaldabaoth":        "Yaldabaoth",
  "Demon Painter":     "DemonPainter",
  "Merope":            "Merope",

  // ── Persona Trinity Souls ──────────────────────────────────────────────────
  "Shin Kanzato":      "Shin_Kanzato",
  "Jun Kanzato":       "Jun_Kanzato",
  "Ryo Kanzato":       "Ryo_Kanzato",
};
