export const personas = [
    "Makoto Yuki",
    "Aigis",
    "Kotone Shiomi",
    "Yukari Takeba",
    "Junpei Iori",
    "Akihiko Sanada",
    "Mitsuru Kirijo",
    "Shinjiro Aragaki",
    "Ken Amada",
    "Koromaru",
    "Fuuka Yamagishi",
    "Chidori Yoshino",
    "Takaya Sakaki",
    "Jin Shirato",
    "Metis",
    "Yu Narukami",
    "Yosuke Hanamura",
    "Chie Satonaka",
    "Yukiko Amagi",
    "Kanji Tatsumi",
    "Rise Kujikawa",
    "Teddie",
    "Naoto Shirogane",
    "Tohru Adachi",
    "Sho Minazuki",
    "Labrys",
    "Ren Amamiya",
    "Ryuji Sakamoto",
    "Ann Takamaki",
    "Morgana",
    "Yusuke Kitagawa",
    "Makoto Niijima",
    "Futaba Sakura",
    "Haru Okumura",
    "Goro Akechi",
    "Sumire Yoshizawa",
    "Takuto Maruki",
    "Zenkichi Hasegawa",
    "Sophia"
];
