export const personas = [
    "Makoto Yuki",
    "Aigis",
    "Kotone Shiomi",
    "Yukari Takeba",
    "Junpei Iori",
    "Akihiko Sanada",
    "Mitsuru Kirijo",
    "Shinjiro Aragaki",
    "Ken Amada",
    "Koromaru",
    "Fuuka Yamagishi",
    "Chidori Yoshino",
    "Takaya Sakaki",
    "Jin Shirato",
    "Metis",
    "Yu Narukami",
    "Yosuke Hanamura",
    "Chie Satonaka",
    "Yukiko Amagi",
    "Kanji Tatsumi",
    "Rise Kujikawa",
    "Teddie",
    "Naoto Shirogane",
    "Tohru Adachi",
    "Sho Minazuki",
    "Labrys",
    "Ren Amamiya",
    "Ryuji Sakamoto",
    "Ann Takamaki",
    "Morgana",
    "Yusuke Kitagawa",
    "Makoto Niijima",
    "Futaba Sakura",
    "Haru Okumura",
    "Goro Akechi",
    "Sumire Yoshizawa",
    "Takuto Maruki",
    "Zenkichi Hasegawa",
    "Sophia",
    "Nagisa Kamishiro",
"Lufel",
"Motoha Arai",
"Shun Kano",
"Riko Tanemura",
"Shoki Ikenami",
"Seiji Shiratori",
"Kotone Montagne",
"Yukimi Fujikawa",
"Tomoko Noge",
"Leo Kamiyama",
"Yaoling Li",
"Kiyoshi Kurotani",
"Kayo Tomiyama",
"Miyu Sahara",
"Toshiya Sumi",
"Haruna Nishimori",
"YUI",
"Minami Miyashita",
"Chizuko Nagao",
"Yumi Shiina",
"Ayaka Sakai",
"Kira Kitazato",
"Masaki Ashiya",
"Runa Dogenzaka",
"Mio Natsukawa",
"Mayumi Hashimoto",
"Manaka Nagao",
"Ichigo Shikano",
 "Tatsuya Suou",
  "Maya Amano",
  "Lisa Silverman",
  "Jun Kurosu",
  "Eikichi Mishina",
  "Baofu",
  "Joker",

];
