export const personas = [
  "Makoto Yuki",
  "Aigis",
  "Kotone Shiomi",
  "Yukari Takeba",
  "Junpei Iori",
  "Akihiko Sanada",
  "Mitsuru Kirijo",
  "Shinjiro Aragaki",
  "Ken Amada",
  "Koromaru",
  // Elizabeth : wielder additionnelle de Thanatos (P4 Arena Ultimax)
  "Elizabeth",
  "Marie",
  "Fuuka Yamagishi",
  "Chidori Yoshino",
  "Takaya Sakaki",
  "Jin Shirato",
  "Metis",
  "Yu Narukami",
  "Yosuke Hanamura",
  "Chie Satonaka",
  "Yukiko Amagi",
  "Kanji Tatsumi",
  "Rise Kujikawa",
  "Teddie",
  "Naoto Shirogane",
  "Tohru Adachi",
  "Sho Minazuki",
  "Labrys",
  "Ren Amamiya",
  "Ryuji Sakamoto",
  "Ann Takamaki",
  "Morgana",
  "Yusuke Kitagawa",
  "Makoto Niijima",
  "Futaba Sakura",
  "Haru Okumura",
  "Goro Akechi",
  "Sumire Yoshizawa",
  "Takuto Maruki",
  "Zenkichi Hasegawa",
  "Sophia",
  "Nagisa Kamishiro",
  "Lufel",
  "Motoha Arai",
  "Shun Kano",
  "Riko Tanemura",
  "Shoki Ikenami",
  "Seiji Shiratori",
  "Kotone Montagne",
  "Yukimi Fujikawa",
  "Tomoko Noge",
  "Leo Kamiyama",
  "Yaoling Li",
  "Kiyoshi Kurotani",
  "Kayo Tomiyama",
  "Miyu Sahara",
  "Toshiya Sumi",
  "Haruna Nishimori",
  "YUI",
  "Minami Miyashita",
  "Chizuko Nagao",
  "Yumi Shiina",
  "Ayaka Sakai",
  "Kira Kitazato",
  "Masaki Ashiya",
  "Runa Dogenzaka",
  "Mio Natsukawa",
  "Mayumi Hashimoto",
  "Manaka Nagao",
  "Ichigo Shikano",
  "Tatsuya Suou",
  "Maya Amano",
  "Lisa Silverman",
  "Jun Kurosu",
  "Eikichi Mishina",
  "Baofu",
  "Katsuya Suou",
  "Ulala Serizawa",
  "Joker",
  "Erina",
  "Aran Hirano",
  "Narumi Nashimoto",
  "Kumi Katayama",

  // Persona Trinity Souls — 2.1 (wielders : on devine le personnage, pas la persona)
  "Shin Kanzato",
  "Jun Kanzato",
  "Ryo Kanzato",

  // Persona 1 — 2.1 (Eriko Kirishima absente : dessin de persona manquant)
  "Naoya Todou",
  "Maki Sonomura",
  "Masao Inaba",
  "Kei Nanjo",
  "Hidehiko Uesugi",
  "Yukino Mayuzumi",
  "Yuka Ayase",
  "Reiji Kido",
  "Eriko Kirishima",
];
