export const portraitsMapPersonae = {
    "Makoto Yuki": "Yuki",
    "Aigis": "Aigis",
    "Kotone Shiomi": "Kotone",
    "Yukari Takeba": "Yukari",
    "Junpei Iori": "Junpei",
    "Akihiko Sanada": "Akihiko",
    "Mitsuru Kirijo": "Mitsuru",
    "Shinjiro Aragaki": "Shinjiro",
    "Ken Amada": "Ken",
    "Koromaru": "Koromaru",
    "Fuuka Yamagishi": "Fuuka",
    "Chidori Yoshino": "Chidori",
    "Takaya Sakaki": "Takaya",
    "Jin Shirato": "Jin",
    "Metis": "Metis",
    "Yu Narukami": "Yu",
    "Yosuke Hanamura": "Yosuke",
    "Chie Satonaka": "Chie",
    "Yukiko Amagi": "Yukiko",
    "Kanji Tatsumi": "Kanji",
    "Rise Kujikawa": "Rise",
    "Teddie": "Teddie",
    "Naoto Shirogane": "Naoto",
    "Tohru Adachi": "Tohru",
    "Sho Minazuki": "Sho",
    "Labrys": "Labrys",
    "Ren Amamiya": "Ren",
    "Ryuji Sakamoto": "Ryuji",
    "Ann Takamaki": "Ann",
    "Morgana": "Morgana",
    "Yusuke Kitagawa": "Yusuke",
    "Makoto Niijima": "Makoto",
    "Futaba Sakura": "Futaba",
    "Haru Okumura": "Haru",
    "Goro Akechi": "Goro",
    "Sumire Yoshizawa": "Sumire",
    "Takuto Maruki": "Maruki",
    "Zenkichi Hasegawa": "Zenkichi",
    "Sophia": "Sophia"
};
