/**
 * musicsMode/database/expert_lyrics.js
 * Paroles pour le mode Music Expert — révélation cumulative, un vers par essai raté.
 *
 * Données GÉNÉRÉES depuis expert_mode_content.md (curé à la main par Hamza) — ne pas
 * éditer les paroles ici, éditer le .md puis régénérer.
 * - Clé = `titre` exact de songs.js. Les instrumentaux n'ont pas d'entrée : une
 *   chanson absente d'ici est hors du tirage Expert Music.
 * - Valeur = les vers dans l'ordre de la chanson, un par palier de révélation.
 * - Paroles stockées BRUTES, titre non masqué : 31 chansons sur 73 citent leur propre
 *   titre. Le masquage est fait à l'affichage via `maskTerms()` (js/gameCore.js), pour
 *   que la fin de partie (victoire ou abandon) n'ait qu'à ré-afficher le texte brut.
 * - Pas de i18n : une parole reste dans sa langue d'origine (CLAUDE.md §5, même
 *   traitement que les titres de musique).
 */
export const expertLyrics = {
  "A Lone Prayer": [
    "Lived in buried memory",
    "With fear-ridden self-consciousness",
    "I'm just a lone prayer",
    "Keep running on the cold track",
    "The hate crazed thoughts just don't stop",
    "As if a dream awake from the dark",
    "The world deletes all I said to you",
  ],
  "Bloody Destiny": [
    "Night Beast",
    "Grab my right arm",
    "Smiling like you got all",
    "Koware kaketa black box daite",
    "Hidden fear overwhelms",
    "Mustn't go back, no control",
    "Shimetsukeru inner soul kataku",
    "Save me from that bloody destiny",
    "How do you feel seizing me now?",
    "You made me like this",
    "From that bloody destiny",
    "Oh God you can't",
    "Let me down",
  ],
  "Dream of Butterfly": [
    "Dream of Butterfly, or is life a dream?",
    "Don't wanna wake up 'cause I'm happier here",
    "Anata ga iru sore dakede yokatta",
    "Tada hitotsu no shinjitsu datta no",
  ],
  "Let Butterflies Spread Until the Dawn": [
    "Inside of agony",
    "Those butterflies crying out",
    "Naki kuchihateru",
    "So boy, help them fly away",
    "Inside of agony",
    "Hageshiku yureru",
    "The world's tears",
    "Falls on him",
    "Until the dawn",
    "Nobody comes",
    "Unbreakable silence slowly hovers in the air",
    "Until the dawn",
    "Nobody comes",
    "Let butterflies spread until the dawn",
  ],
  "School Days": [
    "Looking through my eyes",
    "If perhaps you feel I woke up with you, just smile",
    "Don't you want it, baby?",
    "Keep it real, let's keep it real",
    "Sometime (Kotoba niwa)",
    "I will return at everything (Ienai kedo)",
    "into your love sweet time (Kimi wa kitto shitteru)",
    "I walk (Kotoba niwa)",
    "into your world (Ienai kedo)",
    "and pleased being with you (Kimi wa kitto shitteru)",
  ],
  "Voice": [
    "I hear a voice to cause me arukidasou",
    "Sorezore no michi susumu tame ni",
    "Daremo ga kitto mitsukeruhazusa, shounen no koro miteita yume wo",
    "Sore wo sagashi bokura wa wakare arukidasu",
    "Mou bokura wa kodomo janai yo, dakedo otona ni narikirezuite",
    "Sonna bimyouna hazama no naka de mo ikiru",
  ],
  "Unbreakable Tie": [
    "Really gotta keep it going going",
    "Deep down yeah knowing knowing",
    "What's gonna happen next? Don't know",
    "Can't keep my eyes closed oh man it's gone",
    "Looked everywhere for my identity",
    "Hooked everywhere did I belong to an entity?",
    "I don't know where have I gone wrong?",
    "Wanna try me but you only got hate",
    "Only interested in my fate",
    "And insincerity's not my way",
    "Any interference dodge them away",
    "Let there be light",
    "In the dark night",
    "Gotta get it back it's time I get it back",
    "I wanna bring it back to the good old days",
  ],
  "Burn My Dread": [
    "Dreamless dorm, ticking clock",
    "I walk away from the soundless room",
    "Windless night moonlight melts",
    "My ghostly shadow to the lukewarm gloom",
    "Nightly dance of bleeding swords",
    "Reminds me that I still live",
    "I will burn my dread",
    "I once ran away from the god of fear",
    "And he chained me to despair",
    "Burn my dread",
    "I will break the chain",
    "And run 'til I see the sunlight again",
  ],
  "Mass Destruction": [
    "Fear's awake, anger beats loud, face reality",
    "Never beat charity",
    "The enemy you're fighting covers all society (damn right)",
    "Mommy's not here, gotta fight (all night)",
    "Right here, Shadow, 10 o'clock, direction",
    "Seize the moment, destroy the nation",
    "Your rhyme is slow-motion, give me motivation",
    "Freaked out now, and dead on arrival (what?)",
    "Round up around, spit out, all over",
    "Rhyme like a rolling stone",
    "Comin' a crowd",
    "Watch out, they move, they diss you loud",
    "Guess what this sound, it bombs whole ground",
    "(So round up)",
    "Don't ease your pace, 'cause enemy's brutal",
    "Moment of truth, there ain't no truce",
    "You're the only one, one world, one love",
    "But the battle goes on, Shadows of mass destruction",
  ],
  "Brand New Days": [
    "Sun Light yume wo samasu asa no hikari",
    "mata terashidasu (all over my sight)",
    "kono sekai",
    "togireta yakusoku dake hitori kakaete",
    "mabuta no kinou dake (it's over my blind)",
    "oikaketa",
    "Stay high wasureteta yo",
    "konna ni sukitootta sky blue",
    "kitto kimi ga kureta",
    "True feel kagayaki",
  ],
  "Disconnected": [
    "I keep on reliving the last phase of our days",
    "I'm not sure how I feel anymore",
    "I think I'm homesick but",
    "I don't know (I don't know)",
    "How to go back to a place that's gone",
    "With the change of winds",
    "My heart fell and I can't find it",
    "Feeling empty",
    "Spending days and nights in silence",
    "'Cause no words can explain how I feel",
    "In my mind, and heart",
    "Oh, I don't know what I am but I miss myself",
    "'Cause she's not here anymore",
    "How can I move on? Please tell me",
    "In the end you learn",
    "How to walk alone and be strong (lost without you)",
    "But the little things like thе scent of his cologne",
    "Is a painful remindеr that he's gone",
    "It feels like my heart is suffocating",
    "How do you make amends when you're gone from me?",
    "Even though with a win",
    "How come I feel so lost?",
    "Nothing makes sense to me",
    "I'm so numb, so lost without you",
  ],
  "Don't": [
    "Leave me out",
    "I don't want to fight",
    "But if you insist",
    "There will be consequences",
    "It's like I'm",
    "Getting stomped on my face",
    "While I'm down on the ground (though I)",
    "Survived the worst but the worst is yet to come (and I)",
    "Don't do this to me now I've gone numb (uh)",
    "Do not make me",
    "Already lost my keys",
    "To the door wide shut",
    "Only have one wish",
    "Now it's never gonna come true",
    "Trapped in time",
    "Forever in remorse",
    "How could I ever be",
    "In peace when nothing else matters to me",
  ],
  "Mass Destruction (P3FES)": [
    "I thought told y'all to sit down or get down",
    "I'm about'a hit ground",
    "When I'm in the box, my hits way out of this bounds",
    "Nobody's topping me",
    "(You know it, damn right)",
    "Most of y'alls loving me",
    "(Doing it all night)",
    "Keeping my friends close, and my foes closer",
    "Things getting messy, but I never lick the nose up",
    "As I get older, see things slower",
    "My enemies looking like kids, and I'm the grown up",
    "I'm the next masterpiece made",
    "A new generation came up with the beast \"Ace\"",
    "But I'm the mister nice guy",
    "See me I'm a wise guy",
    "Not a mafioso, but I hustle like Mike",
    "Lay low if you're feelin' me",
    "I take these beats, freaks go crazy with me",
    "So put 'em up in these break with me",
    "So shake with the man, L to the J's, now follow me",
  ],
  "P3 FES": [
    "If you wanna battle, then I'll take it to the street",
    "Where there's no rules",
    "Take off the gloves, ref, please step down",
    "Gotta prove my skills, so get down",
    "My lyrical Dempsey Roll about to smack down now",
    "Gotta shoot to kill and shoot the skill",
    "Don't you be afraid, man's gotta do how it feels",
    "Six to seven to eight to nine, ten",
    "I flip the script to make it to the top ten, go",
    "Dreamless dorm, ticking clock",
    "I walk away from the soundless room",
    "Windless night, moonlight melts",
    "My ghostly shadow to the lukewarm gloom",
  ],
  "A Way of Life": [
    "(I tried hard, but where did we go wrong?",
    "I hope we could, but I won't start all over again)",
    "Midday street walks",
    "Lights fell and dispersed in the air",
    "Nobody stopped to see them fade",
    "Your eyes seemed so innocent",
    "Everything made sense to you but",
    "They didn't to me",
    "Deep inside my mind",
    "(I didn't compromise just for the love)",
    "Deep inside my mind",
    "Believing your words",
    "A way of life, a way of life",
    "I heard you say, \"we were on the same street\"",
    "A way of life, a way of my life",
  ],
  "Soul Phrase": [
    "I believe so strongly",
    "that tomorrow never falls away",
    "Tsukibikari shita",
    "It still awaits",
    "It still carries on through its old ways",
    "till this moment of time",
    "Ano toki Kawashita",
    "Kotoba ga narihibiite",
    "Sasayakana yume",
    "There is no more darkness",
    "no more tears in the rain",
    "no one hurt….",
    "Write me an endless song (when you let go)",
    "As I'll feel so alive",
    "Kurikaesu Soul phrase (I'm walking on my way)",
  ],
  "Wiping All Out": [
    "Been a little while but I'm still battling",
    "Moving fast while you's just prattling",
    "No time for me, no tangling",
    "Hit you in the spot with no angle and",
    "I'm not a princess",
    "(A lot of anger in it)",
    "Not a cutie girlfriend, oh no",
    "Don't you know?",
    "Flashy rhymes coated with spangles",
    "Add some sounds in it, times wangles",
    "Three dots connect to rectangles",
    "Just like music sounds connect in rambles",
    "You cannot run away",
    "(Hell nah, no man can run away)",
    "From me, I stay in your head as",
    "One big threat",
    "It's demolition",
    "Wiping all out (wipe out)",
    "I won't go (yeah, yeah)",
    "Until it's over (once again)",
  ],
  "Time": [
    "Every time, goodbye to yesterday",
    "Greeted by today",
    "Smiling at tomorrow",
    "No one really belongs",
    "Each time, we hope to stay around",
    "I know how you feel",
    "Beyond your words",
    "Time",
    "Old dry winds go by",
    "Lone air comes quietly",
    "Time",
    "Old dry winds go by",
    "Uncertain space you need to fill in",
  ],
  "Changing Seasons": [
    "Sun's up, another day goes by",
    "Look at the time fly",
    "Keep up, the different air gives us that",
    "feeling of being alive",
    "Wander through the warmer colours",
    "across the cooler asphalt",
    "All the leaves go dancing on about",
    "drifting in and out of sight",
    "When summer's over I'll be around if",
    "you need I'll keep you warmed up",
    "When the town dims down I'll be",
    "around if you need I'll light the light",
  ],
  "Color Your Night": [
    "Within the inner heart I plead",
    "For you to talk to me",
    "I want to hear all the good and bad",
    "The new stories you have",
    "As I drift across the sky",
    "The hour hand turns high",
    "So good night",
    "Let me sing a lullaby, love",
    "I'll be seeing you, baby",
  ],
  "Deep Breath Deep Breath": [
    "Feeling all pressured by the peers and the media",
    "Getting jiggy with confined place, I'm telling ya",
    "Anywhere you be from New York to Siberia",
    "Gotta feel your own beat and shake your derrière",
    "I'mma put it down",
    "(down)",
    "Grabbing this crown",
    "(crown)",
    "Lay your dollars on the ground,",
    "Gonna double up now",
    "Six, to five, to four, to three, two",
    "One more time, heavy punchline about to bruise",
    "Let it go, let it out, let it go, let it out",
    "Take a deep breath, deep breath",
    "(Deep breath, deep breath)",
    "Lay low, lay high, lay low, lay high",
    "Until you feel the vibes, now touch the sky",
  ],
  "Full Moon Full Life": [
    "All the journeys start some where with a first step",
    "No one's sure what lies ahead,",
    "Be bold and brave (stand up)",
    "Roads may be rough and tough",
    "Though it will lead some where",
    "(Nothing easy get up and go get it go)",
    "Sometimes it's journey itself that teaches",
    "A lot about the destination not aware of",
    "No matter how far (no matter how far)",
    "How you go (how you go)",
    "How long it may last",
    "(Carpe Diem, no time to waste)",
    "Venture life burn your dread",
    "(You gotta venture life go get it burn your dread)",
  ],
  "It's Going Down Now": [
    "It's those unintelligent monsters, ain't it?",
    "What are they thinking? Please explain it",
    "Don’t really need this crap, can't waste time",
    "What I possess can’t copy and paste down",
    "I'm doing it better",
    "Never settling for another regular",
    "Letter to my enemies, hey I'm telling ya",
    "Breaking you down to the level of molecular",
    "Better be wise when you're choosing battles it's mostly babbles you know one of those big time shady foe foes ain’t worth fighting for",
    "Drop these bars in my sleep, and a few more tricks up my sleeve",
    "It's way too late for you to leave now (get ready)",
    "Disturbing the peace",
    "Look into my eyes",
    "Now tell me the things you blabbing about behind my back",
    "The tenacity I hold, it's hard to break down",
    "It's too late for apologies",
    "It's going down now",
  ],
  "Iwatodai Dorm": [
    "So dance, if you want go ahead",
    "Free to do whatever, I'm chilling on my bed",
    "I'm minding my biz, so mind your own biz",
    "Whatever life gives, We're gonna flow with he said",
    "Hey hey hey, fueling the fire with a burning desire",
    "Everyday we're inspired, but it never expires",
    "But we're gonna chill today",
    "Let me rock the world tomorrow, you know?",
  ],
  "Mass Destruction - Reload (ZUTOMAYO Ver.)": [
    "Aseri ga hamidashita",
    "Ka to itte hizashi ga mabushii hodo",
    "Karada wa daru omojan",
    "Ari gachina kanjou modoki wo",
    "Odotta tote nanimono de monai",
    "Demo imasara hikisagarenai",
    "\"Mina ga neshizumareba boku no deban kuru\"",
  ],
  "When the Moon Reaches for the Stars": [
    "I never felt like so miserable",
    "I never knew I'd think that this would last forever",
    "Baby stay with me",
    "You gotta say now your love flows all over me",
    "I never felt like so different now",
    "It doesn't seem like we've been far apart, so jealous",
    "My life'll turn out",
    "It doesn't seem like it could last for all my life",
    "When stars smile at the moon",
    "Wonder how it looks in your eyes",
    "Just dialing your number",
    "Failed to press the last two",
    "Pray in my heart",
    "When the moon reaches stars",
    "If you hold me tight",
    "Feel your heartbeat so close",
    "Would this last long?",
  ],
  "Want to Be Close -Reload-": [
    "In the light men're crossing over lone shadows",
    "Wearing veiled slight hopes for intimacy",
    "Want to be close",
    "To be close",
  ],
  "Backside Of The TV": [
    "Darkness, endless, despair, fear no more",
    "Coldness, blackened, no sound, feel no pain",
    "Captured, helpless, ultimate, dreadful fate",
    "Powerless, lifeless, no breath, falling down",
    "(Darkness) Lost destiny, (endless) far outcry, (despair) they hear you, fear no more",
    "(Coldness) Numb feeling, (blackened) whole dizziness, (no sound) deep scars, feel no pain",
    "(Captured) No sanity, (helpless) body aching, (ultimate) control your, dreadful fate",
    "(Powerless) Invisible, (lifeless) real enemy, (no breath) ruin your mind, falling deep down",
    "Down down to the base,",
    "The sound you’re about to hear is deep down hip hop,",
    "What you gone do when they start to come up,",
    "Well they’ve already come up to surround you up,",
    "To dis you at a world cup but I guess it depends,",
    "On how you gone behave in that moment,",
    "Huh, a moment of truth tell me what’s really happening,",
    "Their rhyme is nothing but you’ve got everything,",
    "Bro, you’ve got everything but you dunno anything",
  ],
  "Heartbeat, Heartbreak": [
    "Tell me why you did it",
    "Every dream falling apart",
    "Tell me why you did it",
    "After the promise",
    "Still aching, still aching",
    "Oh, baby, I need your love",
    "Looking so different",
    "Glaring street light",
    "Heartbeat, heartbeat",
    "It keeps on pounding",
    "Heartbreak, heartbreak",
    "You tell me goodbye",
    "Heartbeat, heartbeat",
    "It keeps on pounding",
    "Heartbreak, heartbreak",
    "You tell me goodbye",
  ],
  "Heaven": [
    "I can't get my mind out of those memories",
    "Now time to tell them, \"Don't take my dream\"",
    "Still, music keeps on turning me from the words that hurt my soul",
    "Removing doubts from my mind",
    "Those long days passing by from that door",
    "Like late summer, they slowly fade away",
    "Finding ways through the favorite tune",
    "Playing all day with my eyes closed",
    "Those long days passing by from that door",
    "Like late summer, they slowly fade away",
    "Finding ways through the favorite tune, filling me with those sounds",
  ],
  "Never More": [
    "Wasurenai yo, daiji na minna to sugoshita mainichi",
    "Never more, kurai yami mo hitori janai sa",
    "Mitsukedasu yo, daiji na nakushita mono o",
    "Never more, kimi no koe ga kitto sou, boku o michibiku yo",
    "Shinjite ita yo, osanai koro wa tashika ni",
    "Itsu no ma ni ka wasureteta taisetsu na kotoba",
    "Samenai sekai no naka de, sagashi motomete",
    "Boku wa yatto mitsuketa yo, kokoro no oku ni atta",
  ],
  "Pursuing my True Self": [
    "We are living our lives",
    "Abound with so much information",
    "Come on, let go of the remote",
    "Don't you know you're letting all the junk flood in?",
    "I try to stop the flow, double-clicking on the go",
    "But it's no use, hey, I'm being consumed",
    "Loading, loading, loading",
    "Quickly reaching maximum capacity",
    "Warning, warning, warning",
    "Gonna short-circuit my identity (ah)",
    "Get up on your feet, tear down the walls",
    "Catch a glimpse of the hollow world",
    "Snooping 'round town will get you nowhere",
    "You're locked up in your mind",
  ],
  "Reach Out To The Truth": [
    "Now I face out, I hold out",
    "I reach out to the truth of my life",
    "Seeking to seize on the whole moment, yeah",
    "Yeah, naked truth lies only if you realize",
    "Appearing in nobody's eyes 'til they sterilize",
    "Stop the guerrilla warfare to keep it fair",
    "Bro, change your rage to a smarter greater cause",
    "You know the stake is high, stardom is near",
    "Those who sympathized, you died, killers pass you by",
    "Do not waste your time hating flirting guys",
    "Use your might to aid eyes, do justice to them all",
  ],
  "Signs Of Love": [
    "Signs of love overshadowed by dreams",
    "Baby, don't worry 'cause you ain't alone",
    "Only time running days without nights",
    "Tears pass through",
    "He said, \"I'm the one who's got to leave\", I said",
    "\"Nobody's really got to leave 'cause",
    "I don't hear enough explanation",
    "All I need is admiration\"",
    "Big frustration, bro, he goes",
    "\"Life is short, we gave a shot",
    "But didn't work, honey, 'cause we had",
    "A whole lot going on and on and on\"",
    "Signs of love overshadowed by dreams",
    "Baby, don't worry 'cause you ain't alone",
    "Only time running days without nights",
    "Tears pass through",
    "Every time, look at the picture in the frame",
    "Gaze in fascination so hard",
    "You still think that is nothing but love",
    "Rain still falls",
  ],
  "Your Affection": [
    "Withered flowers forget",
    "What they wept for day after day",
    "Withered flowers must blossom",
    "In the stream of tears",
    "They still think of the cause",
    "Turning misery into meaningfulness",
    "Changing day after day",
    "Turning misery into meaningfulness",
    "Changing day after day",
    "Your affection, your affection, taking pride from fear",
    "Past will tell you when to make yourself a hero",
    "Your affection, your affection, your affection",
    "Past will tell you when to make yourself a hero",
  ],
  "Shadow World": [
    "Truth is elusive, it's nowhere to be found",
    "Yeah, the truth can never be written down",
    "It's not in any magazine",
    "You can't see it on your TV screen",
    "Truth is evasive, though you might have the facts",
    "Got it straight, you think, but then it all cracks wide open",
    "You can search the world far and wide",
    "The only truth that you can ever find",
    "Is in another",
    "A soul that's got the same burning need",
    "To find out what's 'neath the cover-up",
    "The one can't be without the true other",
    "So let's get together, see what we can uncover",
    "One that defines your world",
    "Gives you truth and life",
    "One that excels",
    "Special enough to guide your way through",
    "This shadow world",
  ],
  "SNOWFLAKES": [
    "Snowflakes falling on your face",
    "A cold wind blows away",
    "The laughter from this treasured place",
    "But in our memories, it stays",
    "This is where we say farewell",
    "And the wind, it feels a little colder now",
    "Here, times run out like a spell",
    "But laughter's our vow",
    "This is where we saw it through",
    "Thick and thin, this friendship, it was built to last",
    "Here, we swore that we'd be true",
    "To bonds that were forged in our past",
  ],
  "Time To Make History": [
    "It's a war out there everyday",
    "You can't hide from it, you gotta play",
    "By the rules, play it cool",
    "Gotta laugh in the face of the sad disgrace",
    "When your friends and foes look alike on the face of it",
    "They missed their history",
    "But they fight over place in it",
    "Yeah, they fight over place in it",
    "Hard-hit by the times",
    "That's just how your life goes by",
    "I know it's not your fault, you say",
    "But there ain't no other way",
    "So step on up to the plate",
    "Meet your fate",
    "Walkin' straight on into the lion's lair",
    "Step on up, up to the plate",
    "'Cause this ain't no game",
    "It's time to make history, yeah",
  ],
  "Dance!": [
    "Got me something true now",
    "I'm not looking anymore",
    "The times of fakin' love are through now",
    "Sharing real connection's what we're made for",
    "Come on, let go of the remote",
    "Don't you know you're letting all the junk flood in?",
    "I try to stop the flow, double-clicking on the go,",
    "but it's no use hey, I'm being consumed",
    "And I went with the flow, double trouble on the go,",
    "posers kept posing, I'm opposing against these foes",
    "Please know I'm the roses that grew out",
    "from the concrete jungle",
    "Not a day goes by without me thinking 'bout the",
    "Way the world stopped mid-motion",
    "When you walked into my life and we connected",
    "Like we'd shared the same mad potion",
    "Couldn't help but move,",
    "the threads of fate had spun us",
    "Into each other's lives by chance",
    "All this energy's got us inspired now,",
    "We couldn't stop it, just set it free and ... dance!",
  ],
  "Changing Me": [
    "Jibun dake no chizu kakenai de itanda",
    "Dareka no sei ni wa dekinai kara",
    "Seikai wa itsumo mitsu kara nakatta",
    "Iiwake bakari ga umakute",
    "Kizutsuku kurainara kono mamadeī",
    "Sonna jibun wo mitsu ketanda kimi ni deattakara",
    "Kimi no koe kimi no morosa kimi no manazashi",
  ],
  "Maze of Life": [
    "This carousel",
    "Takes us round and round",
    "This labyrinth of life,",
    "You can't tell up from down",
    "Having so much fun",
    "We forget to check",
    "Where this crossroad's taking us",
    "But hey, here we come",
    "This carousel",
    "Spins us round so much",
    "Sometimes you don't know should",
    "You stay on or get off",
    "It's only just begun",
    "Welcome to this wild",
    "Maze of life!",
  ],
  "colorful world": [
    "itsumo no teichōna",
    "monokuro no sekai de",
    "kimitachi to deatte",
    "sora wa isshoku janaku",
    "musū ni iro ga aru to",
    "oshietekureta",
    "yasashii ame furisosogi",
    "kokoro no renzu",
    "haratteiku",
  ],
  "Pull the Trigger": [
    "There ain't no perfect time for any big change",
    "Especially when not ready",
    "More time seems more brutal",
    "'Til it catches you",
    "Either you go with flow or force it",
    "Without determination",
    "But you're not alone in this complication",
    "So come with me",
    "On your mark, y'all get set, then pull the trigger and go",
    "Make a move before they can make an act on you",
    "No one but you can change your own world",
    "Ain't nobody else will do it for you",
  ],
  "Road Less Taken": [
    "Your movie",
    "Your storyline",
    "All decided",
    "Before the curtain",
    "Rises",
    "How does it feel",
    "To be inclined",
    "T'ward fate so certain",
    "How can you change a thing if your life",
    "Has been written into stone?",
    "Your life's been written into plot lines",
    "By another",
    "Can you make it your own?",
    "what you gonna do   what you gonna do",
    "your life plot written by someone but you",
    "what you gonna do   what you gonna do",
    "will you stand up and fight through",
  ],
  "Beneath the Mask": [
    "I'm a shape shifter",
    "At Poe's masquerade",
    "Hiding both face and mind",
    "All free for you to draw",
    "I'm a shape shifter",
    "What else should I be?",
    "Please don't take off my mask",
    "Revealing dark",
  ],
  "Last Surprise": [
    "You try to run me through",
    "Hold on",
    "Think again",
    "Don't you know",
    "What you're starting",
    "But ... you sure ain't got a clue",
    "How bad",
    "This will go",
    "Don't you know",
    "Know my art",
    "(Art of war)",
    "And as you look to the horizon",
    "Not a cloud",
    "But then stormy weather's caught you cold",
    "Seems like it crept up out of nowhere",
    "All around",
    "You it's not quite what you foretold",
    "You'll never see it coming",
    "You'll see that my mind is too fast for eyes",
    "You're done in",
    "By the time it's hit you, your last surprise",
  ],
  "Life Will Change": [
    "It's not a game",
    "I'm not a robot AI challenging you",
    "I'm not a phantom",
    "I'm in your face and",
    "I'm here to see it through",
    "Right before your eyes",
    "Watch us multiply",
    "Come to claim our rights - it's time",
    "As our power grows",
    "Tryin' to stop us shows",
    "(You) Might as well go try'n stop time",
    "So you know that we're out there",
    "Swatting lies in the making",
    "Can't move fast without breaking",
    "Can't hold on or life won't change",
    "And our voices ring out, yeah",
    "Took the mask off to feel free",
    "Fought it out in the debris",
    "Now we know that life will change",
  ],
  "Rivers In the Desert": [
    "It's now or it's never, and I've got to",
    "Make my decision",
    "This time it could be my moment",
    "Is this a mirage or a chance to fulfill my mission?",
    "A river in a dry land",
    "The last ace in a lost hand",
    "A heartbeat for a tin man",
    "Oasis in a singed land",
    "I'm keeping the balance, but I'm standing",
    "On razor's edge now",
    "Move quick or my life is over",
    "One strike, just a feint, then ...",
    "I'm outa his field of vision",
    "Don't ask why I'm ready but I'm ready to",
    "Strike him down now",
    "A chance at a new start",
    "There's no time for indecision",
    "A river in a dry land",
    "The last ace in a lost hand",
    "When the hope of new beginnings burned our feet",
    "Now we need it:",
    "A heartbeat for a tin man",
    "An oasis in a singed land",
    "Remind us what we're here for:",
    "Creating new life",
    "Creating rivers in the desert",
  ],
  "The Whims of Fate": [
    "Champagne flutes and",
    "Dinner suits that",
    "Keep your focus",
    "Away from the cheating hands",
    "Tell me",
    "Does that sexy",
    "Gown say what she's",
    "Got in store for her man?",
    "So we roll the dice,",
    "See where they may fall",
    "Come on, why don't we spin the wheel",
    "See whom it may call",
    "(To) Give into temptation",
    "(To) Win it",
    "(Or) Maybe lose it all",
    "Who knows",
    "Where the whims of fate may lead us",
  ],
  "Wake Up, Get Up, Get Out There": [
    "Who am I?",
    "Am I not unique?",
    "Maybe I'm not here at all",
    "Look, the fakers",
    "Blinding us with lies",
    "The breakers of us all",
    "Oh, it's useless",
    "What could it mean that we're here?",
    "Can we make a difference",
    "If we don't break outta here?",
    "Wake up, get up, get out there",
    "Raise your voice against liars",
    "Feed your anger like fire",
    "Why does nobody want change?",
    "Just imagine you're out there",
    "Swatting lies in the making",
    "Can't move fast without breaking",
    "If you hold on, life won't change",
  ],
  "Hoshi to Bokura to": [
    "seken wa koko ni aru mono dake ga",
    "subete to iukedo",
    "hajimari mo owari mo darenimo",
    "sashizu o sa rezu ni kimete ī",
    "I will follow my heart",
    "kaerō bokura ga",
    "mezashita mirai e",
    "itsu demo doko demo",
    "nozomeba aeru yo",
    "yakusoku wa iranai",
    "bokura korekara mo",
    "onaji hoshi mite iru",
    "hanarete itatte",
    "dakara kyō sayonara",
  ],
  "Colors Flying High": [
    "Your flag, your alibi",
    "Can you hide behind",
    "Claiming might is right?",
    "Raise your fist to the sky",
    "While below your boots",
    "Common men die",
    "Colors fly",
    "Tell us who to love and who to hate",
    "And by the by",
    "Will the mem'ries of our morals fade?",
    "Staying true",
    "To your own convictions in this haze",
    "Is harder to / Do than say",
    "So choose a color to live by",
    "Your goal, your faith, your virtue",
    "Give it all",
    "Be the best cause nothing less will do",
    "You can rule the world with colors flying high",
    "You know that if you stay true",
    "Green or blue",
    "Red or white",
    "You can't lose",
    "With your colors flying high",
  ],
  "I believe": [
    "it's time to",
    "unveil the hype y'all been waiting for",
    "it's time to",
    "bring an end to question of who will win? it's us",
    "I used to have bad feeling",
    "premonition of falling short",
    "now I have no fear",
    "since we're here",
    "to fight it together",
    "I believe",
    "we can fly up in the sky",
    "one day we may just",
    "be able to touch down on a star",
    "off the road we have to go",
    "the roadless path we shall proceed until the end of our roles",
    "there's no turning back for us",
    "cause we will never give up",
  ],
  "No More What Ifs": [
    "People come and they go",
    "Some people may stay with you, though",
    "I am all alone tonight and I kept on",
    "Asking myself questions",
    "Conceited I was at time",
    "I never really doubted myself",
    "But tonight got me thinking about it all",
    "If I am the fool or what not",
    "I do not",
    "Regret with my choices, I'm rather proud, ooh",
    "Yet, I know I won't change",
    "Anything because I can only be me, so",
    "How can I be so sure?",
    "At a crossroads, I'm afraid too",
    "But I can't let fear get the best of me",
    "Someone once said, \"Burn my dread, babe\"",
  ],
  "Our Light": [
    "yume o yume to kizuita yoru, kimi o mitsume mabuta o tojiru",
    "nukumori mo kasaneta te mo koe mo, mezamereba madoromi e to kiete",
    "bokura ga nido to aenakute mo, sugita toki ga itami ni kawatte mo",
    "sono itami de ne michibiite yo, boku o terasu yozora no hoshi e to",
    "amai amai otogi no kuni, kimi to aeta yuganda sekai",
    "itsuwari no shiawase de mo ii to tsugeru kuchi, kimi ga sotto fusagu",
  ],
  "Take Over": [
    "We're rolling deep into your underground crib",
    "Thought I sent a prior notice card for you",
    "We wanna make this party you don't want to skip",
    "Gonna be a show to remember",
    "Take Over it's time to boogie down",
    "Make Over nothing's gonna be the way you might like",
    "(it) Was over when you started with us",
    "You should've thought twice",
    "Walked on thin ice",
    "Hey game's over",
  ],
  "Throw Away Your Mask": [
    "Don't sleep through",
    "dreams that can come true",
    "No more tears shall drop from your cheeks anymore",
    "you won't need to",
    "strive for greatness",
    "Believe in me",
    "That you don't need to suffer from",
    "Anything",
    "You don't need to make a wrong turn",
    "Just requires guidance from above",
    "we don't need to have this conflict",
    "cause I can take you",
    "to the place of delight",
    "give peace",
    "of mind",
    "to the whole world",
  ],
  "Daredevil": [
    "Think twice",
    "Before you pounce",
    "Don't expect us to be nice",
    "Now it's your turn to be the mouse",
    "Thought you had caught us?",
    "We know how your game is played",
    "Straight up devious",
    "Better regret schemes you have made",
    "The shadows call us",
    "Hear the whisper from the night",
    "Take a leap into the dusk",
    "Gotta set wrongs right",
    "Taking over",
    "Ready or not it's the moment",
    "Better off",
    "Stepping aside",
    "Burning with vengeance and sully we fight",
    "Crossed the line",
    "Warned you before",
    "We are unbeaten",
    "No one can question it",
    "Daredevil",
    "You've hit the wall",
    "Did you think you could get away?",
    "You have us to repay",
  ],
  "You Are Stronger": [
    "You are stronger than all things that made you weak",
    "So wake up from long sleep",
    "Don't refuse to be free",
    "Let go",
    "Toughest prison to break out is in your mind",
    "Take my hand",
    "Join the team",
    "Gotta let the dead leaves fall down",
    "Hey it's time to rise up",
    "Egocentric",
    "They made us believe so things would play in",
    "Their favors",
    "Lost and broken",
    "Afraid of changing the way of life",
    "In midst of blurred view",
    "Good ones stumbled to their knees and down they go",
    "Don't let them do it like that",
  ],
  "Axe to Grind": [
    "Hello goodbye",
    "Didn't even try",
    "Do not bore me with pathetic logic",
    "Get a move on",
    "Till you're gone",
    "Outta my sight for your position's tragic",
    "Day and night",
    "Searching all around",
    "Up and down",
    "Controlled by empty words",
    "Wasting away hours",
    "Posing like something you're not",
    "Where's your thought?",
    "Go find an axe to grind",
    "I take hearts but not the mind",
  ],
  "Counter Strike": [
    "You've come a long way",
    "But let me just say",
    "Faking is not enough, so",
    "Counter strike",
    "Ain't it all worth fighting for, no?",
    "Being a device is not what you signed up for",
    "Welcome back to your own game show!",
  ],
  "What You Wish For": [
    "Come on dear pierrot, make a wish",
    "Take your time and decide what's right",
    "Can't you see the light",
    "Time to stop dancing",
    "Around the mirror",
    "In circles",
    "Crying one more tear",
    "Be the key, love",
    "Ready to hop through the looking glass",
    "Feel free, love",
    "Adventures awaiting you",
    "Another maze lies ahead",
    "Don't let it slip",
    "You have come all this way",
    "Stay strong",
    "Stand up now and please make a wish",
  ],
  "Got Your Tail": [
    "Taking up the challenge",
    "No more being a part of the play",
    "Nearly over the edge",
    "Graduated from the cliche",
    "Liberate the puppets",
    "Before irreparably torn",
    "Garner all too many regrets",
    "Why hang on to old morals that are long gone?",
    "If fear is the other choice",
    "Would rather decay than have your way",
    "If we can make it out alive",
    "Would be the talk of the block",
    "Prepared to be shockеd",
  ],
  "Revolution is a Blade": [
    "Greedy as one can be",
    "Unaware of all the tragedy",
    "Never see what's on the line",
    "Letting it slip through the mind",
    "Hungry to make big change",
    "Oblivious to those out of range",
    "Convinced you are right",
    "Blinded by the light",
    "Visions of leading something worthy",
    "Possibilities waiting high above",
    "Will it ever be enough",
    "Can't forget that not all will be as tough",
    "Know that where you stand is a fallen land",
    "Not anything grand",
    "Is it so hard to pursue",
    "Life of solitude off the radar",
    "And discard the vanguard",
  ],
  "Truth or Dare": [
    "Vanquish every hint of doubt",
    "'Cause here lousy vibes are out of bounds",
    "Call us contumelious",
    "Couldn't care less nobody wanted to impress",
    "Working on a thorough purge",
    "Move away or be knocked off your perch",
    "We strive for the greater good",
    "Firm ground we stood even when misunderstood",
    "Took for granted the easier way of life",
    "The moment to now decide",
    "Is it worth causing all the endless strife",
    "Hear your voice burning inside",
  ],
  "Ambitions and Visions": [
    "Look like you don't care",
    "Walking the dust off",
    "Is that all you do",
    "Is that all you're made of",
    "Whatever ain't right",
    "Brought it on yourself",
    "Revisit your act",
    "Results are parallel",
    "Living 'long a guideline",
    "Been there, done that",
    "Caught up in drear",
    "Instead of being bitter",
    "Pack up",
    "Go grab your gear",
    "Chit chat, forget the lame brickbats",
    "Grow old, a chronicle to be told",
    "(Don't waste it)",
    "Map out our route as the driver",
    "We'll hit the tip-top of an adventure",
    "Ready to relish everyday",
    "Desire - caught fire",
    "Lighting up the way",
  ],
  "Fatal Desire": [
    "What you think for",
    "Ain't over dull?",
    "Drop them off",
    "Used to jabber",
    "Wake up from deep mire",
    "Taking the mask off",
    "Let it burn up to break the stinky spell",
    "As we meet your plight right here",
    "Helpin' to bring fix up the spoils",
    "Hold on",
    "That is all we need to ponder over",
    "Gaze and shout",
    "Redeem the heart that you ever been",
    "Regain sense of fever (imaging)",
    "Fight it, cease the coward fake mind sealed",
    "Break in, break out",
    "Time to take it over",
  ],
  "Last Strike": [
    "What are you searching for?",
    "Seen this before",
    "Like nothing but a joke",
    "Your sick imagination",
    "Pure illusion",
    "Escaping from the hole",
    "Without the fame and fortune",
    "Dream got so broken",
    "Don't play the alpha to me",
    "I'm not the fodder you call when you need a scapegoat",
    "Don't break a line in between",
    "Pull this lifeless frame",
    "To ash",
    "Drench your bumping dark in flame",
    "Ready to seal the past",
    "Combat your lie",
    "Driving for burning lust",
    "By my decide",
    "It's our chance to strike",
    "To earn comeback",
    "Pick up your jokey pride",
    "And step off stage to say goodbye",
  ],
  "Seize the Light": [
    "Strum for memo",
    "One more daring try",
    "In secret",
    "Step on shadow",
    "One more starry night",
    "Hide in shade",
    "Trapped in the days",
    "Put the chord in my case",
    "Add \"Leave me away\" in every phrase",
    "Prayed for escape",
    "Caressing the print",
    "Maybe I am not afraid",
    "of any one say I'm locking away",
    "myself in weight",
    "Trace my own light by all the coordinate",
    "Chase the times to celebrate, once that we date",
    "Take the stage in day and after day",
    "that I am dreaming",
    "The day I await when holding my brave",
  ],
  "Shadow Loop": [
    "Get from the bump back",
    "Pick up the troubles scattered all 'round",
    "No time to daze, right?",
    "Fancy your fevers",
    "'Cause no one brought such crise before",
    "But the game is not over",
    "Night falls and knock-knock",
    "Here comes the judgement",
    "Fix what you messed up",
    "Take back the pungent reasons",
    "Throw up the backlog",
    "Turn to our rhythm",
    "Rush into loophole",
    "Raze the envelope in your fiction",
    "So-called the fake right",
    "Punk dress is now a fig leaf you wear",
    "Hey, give up the foul mind",
    "Send to your high lord",
    "Desire wonders to hope light",
    "Hurry to surrender",
  ],
  "Wake Up Your Hero": [
    "Waking up my no-name hero",
    "Coming over time to final show",
    "Throw up fancy cover into shadow",
    "Give it up",
    "to all your buck",
    "Giving pardon but",
    "basing where you go",
    "Sending off the faker hide in ego",
    "Never breaking me down as you know",
    "Why not try to flutter with my tempo",
    "Dancing to the funk",
    "And knock it down",
    "Taking mettle with you",
    "Let desire light up",
    "Setting fire on the thorns",
  ],
  "Wonder Light": [
    "My Mr.Right",
    "Scarlet eyes",
    "Watching how far made me move",
    "Together take stage to sing out all my brave",
    "Sank'in the dream",
    "that all mornings are departed from me",
    "Try to rided",
    "Come on my girl just only move your lips",
    "Been ready",
    "to greet my dawn star that waiting in deep",
    "I see waning lonely shimmers in waving",
    "About time to give up in the final night",
  ],
  "Show Stealer": [
    "Mosaic, staring blankly down at me.",
    "Flashing piece by piece,",
    "I want to set it all free",
    "Red curtains drawn shut yet again",
    "What's left",
    "Alone, standing in the dark?",
    "I'm lost",
    "Trapped in a thousand lies",
    "Have to find passions abandoned",
    "What you want",
    "What you wish",
    "Answer lies in your heart",
    "Hopes and dreams start to beat",
    "Time to take the stage",
    "Round of applause",
    "One more time",
    "Spotlight shines in the dark",
    "Sing and dance,",
    "burning soul in you",
    "Now set me free",
    "See the night",
    "Waiting for the day to come",
    "We'll chase even the stardust",
    "Til the fight is done",
    "All I know",
    "Lost in finding who I truly am",
    "Flames will guide the way to follow",
  ],
};

