export const musicTitles = [
  "A Way of Life",
  "Ambitions and Visions",
  "Backside Of The TV",
  "Beneath the Mask",
  "Brand New Days",
  "Burn My Dread",
  "Changing Seasons",
  "Colors Flying High",
  "Colour Your Night",
  "Dance!",
  "Daredevil",
  "Deep Breath Deep Breath",
  "Disconnected",
  "Don't",
  "Full Moon Full Life",
  "Heartbeat, Heartbreak",
  "Heaven",
  "I believe",
  "It's Going Down Now",
  "Iwatodai Dorm",
  "Last Surprise",
  "Layer Cake",
  "Life Will Change",
  "Mass Destruction",
  "Memories of You",
  "Never More",
  "No More What Ifs",
  "Our Light",
  "Pursuing my True Self",
  "Reach Out To The Truth",
  "Rivers In the Desert",
  "Secret Base",
  "Shadow World",
  "Shadow Loop",
  "Signs Of Love",
  "SNOWFLAKES",
  "Soul Phrase",  
  "specialist",
  "Take Over",
  "The Days When My Mother Was There",
  "The Whims of Fate",
  "Time To Make History",
  "Tokyo Daylight",
  "Wake Up, Get Up, Get Out There",
  "Wake Up Your Hero",
  "When the Moon Reaches for the Stars",
  "Wiping All Out",
  "You Are Stronger",
  "Your Affection"
];
