export const musicTitles = [
  "A Way of Life",
  "Backside Of The TV",
  "Beneath the Mask",
  "Burn My Dread",
  "Changing Seasons",
  "Colors Flying High",
  "Colour Your Night",
  "Dance!",
  "Daredevil",
  "Disconnected",
  "Don't",
  "Full Moon Full Life",
  "Heartbeat, Heartbreak",
  "Heaven",
  "I believe",
  "It's Going Down Now",
  "Iwatodai Dorm",
  "Last Surprise",
  "Life Will Change",
  "Mass Destruction",
  "Memories of You",
  "Never More",
  "No More What Ifs",
  "Our Light",
  "Pursuing my True Self",
  "Reach Out To The Truth",
  "Rivers In the Desert",
  "Secret Base",
  "Shadow World",
  "Signs Of Love",
  "SNOWFLAKES",
  "specialist",
  "Take Over",
  "The Days When My Mother Was There",
  "The Whims of Fate",
  "Time To Make History",
  "Tokyo Daylight",
  "Wake Up, Get Up, Get Out There",
  "When the Moon Reaches for the Stars",
  "Wiping All Out",
  "You Are Stronger",
  "Your Affection"
];
