export const musicTitles = [
  "A Lone Prayer",
  "A Way of Life",
  "Ambitions and Visions",
  "Arial Of The Soul",
  "Backside Of The TV",
  "Beneath the Mask",
  "Blood Destiny",
  "Brand New Days",
  "Burn My Dread",
  "Changing Seasons",
  "Changing Me",
  "Colors Flying High",
  "Color Your Night",
  "colorful world",
  "Dance!",
  "Daredevil",
  "Deep Breath Deep Breath",
  "Disconnected",
  "Don't",
  "Dream of Butterfly",
  "Fatal Desire",
  "Full Moon Full Life",
  "Heartbeat, Heartbreak",
  "Heaven",
  "I believe",
  "It's Going Down Now",
  "Iwatodai Dorm",
  "Last Strike",
  "Last Surprise",
  "Layer Cake",
  "Let Butterflies Spread Until the Dawn",
  "Life Will Change",
  "Maki",
  "Mass Destruction",
  "Mass Destruction - Reload (ZUTOMAYO Ver.)",
  "Map I",
  "Maya Theme",
  "Memories of You",
  "Never More",
  "No More What Ifs",
  "Our Light",
  "Pursuing my True Self",
  "Pull the Trigger",
  "Reach Out To The Truth",
  "Road Less Taken",
  "Satomi Tadashi Pharmacy Theme",
  "Rivers In the Desert",
  "School Days",
  "Secret Base",
  "Seize the Light",
  "Seven Sisters Theme",
  "Shadow World",
  "Shadow Loop",
  "Signs Of Love",
  "SNOWFLAKES",
  "Soul Phrase",  
  "specialist",
  "Take Over",
  "The Battle for Everyone's Souls",
  "Maze of Life",
  "When Mother Was There",
  "The Whims of Fate",
  "Time To Make History",
  "Tokyo Daylight",
  "Unbreakable Tie",
  "Voice",
  "Wake Up, Get Up, Get Out There",
  "Wake Up Your Hero",
  "When the Moon Reaches for the Stars",
  "Wiping All Out",
  "Wonder Light",
  "You Are Stronger",
  "Your Affection"
];
